const AdminPage=(()=>{
  let token="",profile=null,current="dashboard",page=1,search="";
  const menus=[['dashboard','Dashboard'],['users','Peserta'],['schools','Sekolah'],['seasons','Season'],['questions','Bank Soal'],['quiz','Challenge / Quiz'],['leaderboard','Leaderboard'],['winners','Pemenang'],['rewards','Hadiah'],['materials','Materi Edukasi'],['announcements','Pengumuman'],['fraud','Fraud & Review'],['reports','Laporan'],['activity','Activity Log','SUPERADMIN'],['settings','Settings','SUPERADMIN'],['admins','Admin Management','SUPERADMIN']];
  const configs={
    users:{endpoint:'adminListUsers',title:'Peserta',fields:['Name','NIS','SchoolName','Class','Email','WhatsApp','Status','Point','CreatedAt'],search:'Nama, NIS, atau email',actions:['detail','status','reset']},
    schools:{endpoint:'adminListSchools',title:'Sekolah',fields:['SchoolName','NPSN','Type','District','Status','ParticipantCount'],search:'Nama sekolah atau NPSN',create:'school',actions:['editSchool','schoolStatus']},
    seasons:{endpoint:'adminGetSeasons',title:'Season',fields:['Name','Theme','StartDate','EndDate','QuestionCount','PointPerQuestion','Reward','Status'],search:'Nama season',create:'season',actions:['editSeason','seasonStatus','duplicateSeason']},
    questions:{endpoint:'adminGetQuestions',title:'Bank Soal',fields:['Question','Category','Difficulty','Point','Status','UpdatedAt'],search:'Pertanyaan atau kategori',create:'question',actions:['editQuestion','questionStatus']},
    quiz:{endpoint:'adminGetQuizSessions',title:'Challenge / Quiz',fields:['UserID','SeasonID','StartedAt','FinishedAt','Correct','Wrong','Score','TotalPoint','Duration','Status'],search:'User atau season'},
    rewards:{endpoint:'adminGetRewards',title:'Hadiah',fields:['SeasonID','WinnerID','RewardName','Nominal','Provider','Status','SentAt'],search:'Season, pemenang, atau hadiah'},
    materials:{endpoint:'adminGetMaterials',title:'Materi Edukasi',fields:['Title','Category','Status','PublishedAt','UpdatedAt'],search:'Judul atau kategori',create:'material',actions:['editMaterial']},
    announcements:{endpoint:'adminGetAnnouncements',title:'Pengumuman',fields:['Title','Type','StartDate','EndDate','Status','UpdatedAt'],search:'Judul pengumuman',create:'announcement',actions:['editAnnouncement']},
    fraud:{endpoint:'adminGetFraudLogs',title:'Fraud & Review',fields:['UserID','SessionID','Type','Score','Description','Status','CreatedAt'],search:'User atau session',actions:['reviewFraud']},
    activity:{endpoint:'adminGetActivityLogs',title:'Activity Log',fields:['CreatedAt','UserID','Action','Entity','Description'],search:'Action, user, atau deskripsi'},
    admins:{endpoint:'adminGetAdmins',title:'Admin Management',fields:['Name','Email','Role','Status','LastLogin'],search:'Nama atau email',create:'admin',actions:['editAdmin','reset']}
  };
  const el=(tag,attrs={},text='')=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('data-')?n.setAttribute(k,v):n[k]=v);if(text!==undefined)n.textContent=text;return n};
  async function init(){const session=Auth.requireLogin();if(!session)return;token=session.token;try{profile=(await apiPost('getProfile',{},token)).data;if(!['ADMIN','SUPERADMIN'].includes(profile.Role)){location.replace(Utils.pageUrl('app.html',{reason:'forbidden'}));return}Utils.setText('[data-admin-name]',profile.Name);Utils.setText('[data-admin-role]',profile.Role);buildNav();document.querySelector('#admin-loading').hidden=true;document.querySelector('#admin-shell').hidden=false;window.addEventListener('hashchange',route);route()}catch(error){document.querySelector('#admin-loading').textContent=Utils.errorMessage(error)}}
  function buildNav(){const nav=document.querySelector('#admin-nav');menus.filter(m=>!m[2]||profile.Role===m[2]).forEach(m=>{const b=el('button',{class:'admin-nav-button',type:'button','data-view':m[0]},m[1]);b.onclick=()=>{location.hash=m[0];closeDrawer()};nav.append(b)})}
  function route(){current=(location.hash||'#dashboard').slice(1);if(!menus.some(m=>m[0]===current))current='dashboard';if(['activity','settings','admins'].includes(current)&&profile.Role!=='SUPERADMIN')current='dashboard';page=1;search='';document.querySelectorAll('.admin-nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===current));document.querySelector('#page-title').textContent=(menus.find(m=>m[0]===current)||[])[1]||'Dashboard';load()}
  async function load(){const view=document.querySelector('#admin-view');view.replaceChildren(el('div',{class:'admin-skeleton'},'Memuat data…'));try{if(current==='dashboard')return renderDashboard((await apiPost('adminDashboardStats',{},token)).data);if(current==='leaderboard')return renderLeaderboard();if(current==='winners')return renderWinners();if(current==='reports')return renderReports();if(current==='settings')return renderSettings();return renderTable(configs[current],(await apiPost(configs[current].endpoint,{page,limit:20,search},token)).data)}catch(error){view.replaceChildren(errorState(error))}}
  function errorState(error){const box=el('div',{class:'admin-error'});box.append(el('p',{},Utils.errorMessage(error)));const b=el('button',{class:'button button-primary',type:'button'},'Coba Lagi');b.onclick=load;box.append(b);return box}
  function toolbar(config){const bar=el('div',{class:'admin-toolbar'}),input=el('input',{placeholder:config.search||'Cari…',value:search});input.onkeydown=e=>{if(e.key==='Enter'){search=input.value.trim();page=1;load()}};bar.append(input);const find=el('button',{class:'button button-secondary',type:'button'},'Cari');find.onclick=()=>{search=input.value.trim();page=1;load()};bar.append(find);if(config.create){const add=el('button',{class:'button button-primary',type:'button'},'+ Tambah');add.onclick=()=>openCreate(config.create);bar.append(add)}return bar}
  function renderTable(config,data){const view=document.querySelector('#admin-view');view.replaceChildren();view.append(toolbar(config));const rows=data.items||[];if(!rows.length){view.append(el('div',{class:'admin-empty'},'Belum ada data untuk filter ini.'));return}const wrap=el('div',{class:'admin-table-wrap'}),table=el('table',{class:'admin-table'}),head=el('thead'),trh=el('tr');config.fields.forEach(f=>trh.append(el('th',{},label(f))));if(config.actions)trh.append(el('th',{},'Aksi'));head.append(trh);table.append(head);const body=el('tbody');rows.forEach(row=>{const tr=el('tr');config.fields.forEach(f=>tr.append(el('td',{},format(row[f]))));if(config.actions){const td=el('td'),actions=el('div',{class:'admin-actions'});config.actions.forEach(a=>{const b=el('button',{type:'button'},actionLabel(a));b.onclick=()=>doAction(a,row);actions.append(b)});td.append(actions);tr.append(td)}body.append(tr)});table.append(body);wrap.append(table);view.append(wrap);const p=data.pagination;if(p){const nav=el('div',{class:'admin-pagination'});nav.append(el('span',{},`${p.total} data · Halaman ${p.page}/${p.pages||1}`));const buttons=el('div',{class:'admin-actions'}),prev=el('button',{disabled:p.page<=1},'Sebelumnya'),next=el('button',{disabled:p.page>=p.pages},'Berikutnya');prev.onclick=()=>{page--;load()};next.onclick=()=>{page++;load()};buttons.append(prev,next);nav.append(buttons);view.append(nav)}}
  function label(v){return v.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/ID$/,' ID')}
  function format(v){if(v===true)return'Ya';if(v===false)return'Tidak';if(v===null||v===undefined||v==='')return'—';return String(v).length>120?String(v).slice(0,117)+'…':String(v)}
  function actionLabel(a){return({detail:'Detail',status:'Status',reset:'Reset password',editSchool:'Edit',schoolStatus:'Aktif/Nonaktif',editSeason:'Edit',seasonStatus:'Ubah status',duplicateSeason:'Duplikat',editQuestion:'Edit',questionStatus:'Aktif/Nonaktif',editMaterial:'Edit',editAnnouncement:'Edit',reviewFraud:'Review',editAdmin:'Role/Status'})[a]||a}
  async function doAction(action,row){try{if(action==='detail'){const d=(await apiPost('adminGetUser',{userId:row.UserID},token)).data;return showDetail(d)}if(action==='status'){const status=prompt('Status: ACTIVE, PENDING, SUSPENDED, BLOCKED',row.Status);if(!status)return;let reason='';if(['SUSPENDED','BLOCKED'].includes(status))reason=prompt('Alasan wajib:','')||'';if(!confirm(`Ubah status peserta menjadi ${status}?`))return;await apiPost('adminUpdateUserStatus',{userId:row.UserID,status,reason},token)}else if(action==='reset'){const password=prompt('Password sementara (minimal 8 karakter):','');if(!password)return;await apiPost('adminResetUserPassword',{userId:row.UserID,temporaryPassword:password},token)}else if(action==='schoolStatus'){const status=row.Status==='ACTIVE'?'INACTIVE':'ACTIVE';if(!confirm(`Ubah status sekolah menjadi ${status}?`))return;await apiPost('adminChangeSchoolStatus',{schoolId:row.SchoolID,status},token)}else if(action==='seasonStatus'){const status=prompt('Status tujuan: DRAFT, SCHEDULED, ACTIVE, FINISHED, ARCHIVED',row.Status);if(!status||!confirm(`Ubah season menjadi ${status}?`))return;await apiPost('adminChangeSeasonStatus',{seasonId:row.SeasonID,status},token)}else if(action==='duplicateSeason'){const name=prompt('Nama salinan:',row.Name+' (Salinan)');if(!name)return;await apiPost('adminDuplicateSeason',{seasonId:row.SeasonID,name},token)}else if(action==='questionStatus'){const status=row.Status==='ACTIVE'?'INACTIVE':'ACTIVE';await apiPost('adminChangeQuestionStatus',{questionId:row.QuestionID,status},token)}else if(action==='reviewFraud'){const status=prompt('REVIEWED, RESOLVED, atau CONFIRMED','REVIEWED');if(!status)return;await apiPost('adminReviewFraud',{fraudLogId:row.FraudLogID,status},token)}else if(action==='editAdmin'){const role=prompt('Role ADMIN atau SUPERADMIN',row.Role),status=prompt('Status',row.Status);if(!role||!status||!confirm('Simpan perubahan admin?'))return;await apiPost('adminUpdateAdmin',{userId:row.UserID,role,status},token)}else return openCreate(action.replace('edit','').toLowerCase(),row);toast('Perubahan berhasil disimpan.');load()}catch(error){toast(Utils.errorMessage(error),'error')}}
  function showDetail(data){const u=data.user,s=data.stats,body=el('div');body.append(el('p',{},`${u.Name} · ${u.NIS} · ${u.Email}`),el('p',{},`Status ${u.Status} · Point ${s.totalPoint} · Quiz ${s.quizCompleted} · Benar ${s.correctAnswers} · Rata-rata ${s.averageScore}`));openDialog('Detail Peserta',body,null)}
  const forms={school:[['schoolName','Nama sekolah'],['npsn','NPSN'],['type','Jenis (SMA/SMK/MA/Sederajat)'],['address','Alamat'],['district','Kecamatan']],season:[['name','Nama season'],['theme','Tema'],['description','Deskripsi','textarea'],['startDate','Tanggal mulai','date'],['endDate','Tanggal selesai','date'],['reward','Reward'],['questionCount','Jumlah soal','number'],['pointPerQuestion','Point/soal','number'],['maxAttempt','Max attempt','number'],['quizDuration','Durasi detik','number']],question:[['category','Kategori'],['question','Pertanyaan','textarea'],['optionA','Pilihan A'],['optionB','Pilihan B'],['optionC','Pilihan C'],['optionD','Pilihan D'],['correctAnswer','Jawaban benar'],['explanation','Pembahasan','textarea'],['difficulty','Difficulty'],['point','Point','number']],material:[['title','Judul'],['category','Kategori'],['thumbnail','Thumbnail URL'],['content','Isi','textarea'],['videoUrl','Video URL'],['status','Status']],announcement:[['title','Judul'],['content','Konten','textarea'],['type','Type'],['startDate','Mulai','date'],['endDate','Selesai','date'],['status','Status']],admin:[['name','Nama'],['email','Email','email'],['password','Password','password'],['role','Role']]};
  function openCreate(kind,row={}){const spec=forms[kind];if(!spec)return;const body=el('div');spec.forEach(([name,title,type='text'])=>{const labelNode=el('label');labelNode.append(el('span',{},title));const key={schoolName:'SchoolName',npsn:'NPSN',type:'Type',address:'Address',district:'District',name:'Name',theme:'Theme',description:'Description',startDate:'StartDate',endDate:'EndDate',reward:'Reward',questionCount:'QuestionCount',pointPerQuestion:'PointPerQuestion',maxAttempt:'MaxAttempt',quizDuration:'QuizDuration',category:'Category',question:'Question',optionA:'OptionA',optionB:'OptionB',optionC:'OptionC',optionD:'OptionD',correctAnswer:'CorrectAnswer',explanation:'Explanation',difficulty:'Difficulty',point:'Point',title:'Title',thumbnail:'Thumbnail',content:'Content',videoUrl:'VideoURL',status:'Status',email:'Email',role:'Role'}[name]||name;const input=type==='textarea'?el('textarea',{name,rows:4}):el('input',{name,type});input.value=row[key]??'';labelNode.append(input);body.append(labelNode)});openDialog((Object.keys(row).length?'Edit ':'Tambah ')+kind,body,async()=>{const payload=Object.fromEntries(new FormData(body.closest('form')).entries());if(kind==='school'){if(row.SchoolID)payload.schoolId=row.SchoolID;await apiPost('adminSaveSchool',payload,token)}else if(kind==='season'){if(row.SeasonID){payload.seasonId=row.SeasonID;await apiPost('adminUpdateSeason',payload,token)}else await apiPost('adminCreateSeason',payload,token)}else if(kind==='question'){if(row.QuestionID){payload.questionId=row.QuestionID;await apiPost('adminUpdateQuestion',payload,token)}else await apiPost('adminCreateQuestion',payload,token)}else if(kind==='material'){if(row.MaterialID)payload.materialId=row.MaterialID;await apiPost('adminSaveMaterial',payload,token)}else if(kind==='announcement'){if(row.AnnouncementID)payload.announcementId=row.AnnouncementID;await apiPost('adminSaveAnnouncement',payload,token)}else await apiPost('adminCreateAdmin',payload,token);toast('Data berhasil disimpan.');load()})}
  function openDialog(title,body,onSave){const d=document.querySelector('#admin-dialog');document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-body').replaceChildren(body);document.querySelector('#dialog-save').hidden=!onSave;d.onclose=async()=>{if(d.returnValue==='save'&&onSave)try{await onSave()}catch(error){toast(Utils.errorMessage(error),'error')}};d.showModal()}
  function renderDashboard(data){const view=document.querySelector('#admin-view');view.replaceChildren();const stats=el('div',{class:'admin-stats'});Object.entries(data.stats).forEach(([k,v])=>{const c=el('article',{class:'admin-card admin-stat'});c.append(el('strong',{},format(v)),el('span',{},label(k)));stats.append(c)});view.append(stats);const quick=el('div',{class:'quick-actions'});[['+ Tambah Season','season'],['+ Tambah Soal','question'],['+ Tambah Sekolah','school'],['+ Buat Pengumuman','announcement']].forEach(x=>{const b=el('button',{class:'button button-secondary'},x[0]);b.onclick=()=>openCreate(x[1]);quick.append(b)});const lb=el('button',{class:'button button-primary'},'Lihat Leaderboard');lb.onclick=()=>location.hash='leaderboard';quick.append(lb);view.append(quick);const charts=el('div',{class:'admin-charts'});Object.entries(data.charts).forEach(([name,items])=>{const card=el('article',{class:'admin-card'});card.append(el('h3',{},label(name)));const chart=el('div',{class:'mini-chart'}),max=Math.max(1,...items.map(x=>Number(x.value)));items.forEach(x=>{const bar=el('div',{class:'mini-bar'}),i=el('i');i.style.height=`${Math.max(3,Number(x.value)/max*100)}px`;bar.append(i,el('span',{},`${x.label} (${x.value})`));chart.append(bar)});card.append(chart);charts.append(card)});view.append(charts)}
  async function renderLeaderboard(){const view=document.querySelector('#admin-view'),bar=el('div',{class:'admin-toolbar'}),season=el('input',{placeholder:'Season ID'}),type=el('select');type.append(new Option('Peserta','participant'),new Option('Sekolah','school'));const b=el('button',{class:'button button-primary'},'Tampilkan');b.onclick=async()=>{try{const action=type.value==='school'?'getSchoolLeaderboard':'adminGetLeaderboard',r=type.value==='school'?await apiGet(action,{seasonId:season.value,limit:100}):await apiPost(action,{seasonId:season.value,limit:100},token),items=r.data.entries||[];renderSimple(items)}catch(e){toast(Utils.errorMessage(e),'error')}};bar.append(season,type,b);view.replaceChildren(bar,el('div',{class:'admin-empty'},'Pilih season untuk melihat leaderboard.'))}
  function renderSimple(items){const view=document.querySelector('#admin-view');if(!items.length)return view.append(el('div',{class:'admin-empty'},'Data belum tersedia.'));const fields=Object.keys(items[0]),data={items,pagination:null};renderTable({fields,title:'Data'},data)}
  function renderWinners(){const view=document.querySelector('#admin-view'),card=el('div',{class:'admin-card'}),season=el('input',{placeholder:'Season ID'}),reason=el('textarea',{placeholder:'Alasan/catatan',rows:3}),out=el('div',{class:'admin-card'});out.hidden=true;let candidate,winner,reward;async function call(action,payload){try{const r=await apiPost(action,payload,token);toast(r.message);return r.data}catch(e){toast(Utils.errorMessage(e),'error')}}const buttons=el('div',{class:'quick-actions'});[['Preview',async()=>{const d=await call('adminPrepareSeasonFinalization',{seasonId:season.value});if(d){candidate=d.candidate;out.hidden=false;out.textContent=candidate?`${candidate.name} · ${candidate.schoolName} · ${candidate.point} point · Fraud ${candidate.fraudStatus}`:'Tidak ada kandidat.'}}],['Disqualify',async()=>{if(!candidate||!confirm('Diskualifikasi kandidat ini?'))return;await call('adminDisqualifyCandidate',{seasonId:season.value,userId:candidate.userId,reason:reason.value})}],['Finalize',async()=>{if(!candidate||!confirm('Finalisasi pemenang?'))return;const d=await call('adminFinalizeWinner',{seasonId:season.value,userId:candidate.userId,reason:reason.value});if(d){winner=d.winner;reward=d.reward}}],['Verify',async()=>{const d=await call('adminVerifyWinner',{winnerId:winner?.winnerId,seasonId:season.value,destinationNumber:prompt('Nomor tujuan:','')||'',notes:reason.value});if(d){winner=d.winner;reward=d.reward}}],['Reward Sent',async()=>{reward=await call('adminUpdateRewardStatus',{rewardId:reward?.RewardID||reward?.rewardId,status:'SENT',notes:reason.value})}],['Publish',async()=>{if(confirm('Publikasikan pemenang?'))await call('adminPublishWinner',{winnerId:winner?.winnerId,seasonId:season.value})}]].forEach(([name,fn])=>{const b=el('button',{class:'button button-secondary'},name);b.onclick=fn;buttons.append(b)});card.append(el('h2',{},'Winner Management'),season,reason,buttons,out);view.replaceChildren(card)}
  function renderReports(){const view=document.querySelector('#admin-view'),card=el('div',{class:'admin-card'}),type=el('select');['participants','schools','seasons','quiz','leaderboard','winner','reward','point','fraud'].forEach(x=>type.add(new Option(x,x)));const season=el('input',{placeholder:'Season ID (opsional)'}),school=el('input',{placeholder:'School ID (opsional)'}),start=el('input',{type:'date'}),end=el('input',{type:'date'}),b=el('button',{class:'button button-primary'},'EXPORT CSV');b.onclick=async()=>{try{const d=(await apiPost('adminExportReport',{type:type.value,filters:{seasonId:season.value,schoolId:school.value,startDate:start.value,endDate:end.value}},token)).data,blob=new Blob([d.csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=d.filename;a.click();URL.revokeObjectURL(a.href);toast(`${d.count} baris diekspor.`)}catch(e){toast(Utils.errorMessage(e),'error')}};const print=el('button',{class:'button button-secondary'},'CETAK / PDF');print.onclick=()=>window.print();card.append(el('h2',{},'Laporan Terfilter'),type,season,school,start,end,b,print);view.replaceChildren(card)}
  async function renderSettings(){try{const rows=(await apiPost('adminGetSettings',{},token)).data,view=document.querySelector('#admin-view'),card=el('div',{class:'admin-card'});rows.forEach(r=>{const line=el('div',{class:'admin-toolbar'}),input=el('input',{value:String(r.Value)}),b=el('button',{class:'button button-secondary'},'Simpan');b.onclick=async()=>{try{await apiPost('adminUpdateSetting',{key:r.Key,value:input.value},token);toast('Setting berhasil diperbarui.')}catch(e){toast(Utils.errorMessage(e),'error')}};line.append(el('strong',{},r.Key),input,b);card.append(line)});view.replaceChildren(card)}catch(e){document.querySelector('#admin-view').replaceChildren(errorState(e))}}
  function toast(message,type='success'){const n=document.querySelector('#admin-toast');n.textContent=message;n.className='admin-toast '+type;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,3500)}
  function closeDrawer(){document.querySelector('#admin-sidebar').classList.remove('open');document.querySelector('[data-backdrop]').hidden=true}
  async function logout(button){Utils.setButtonLoading(button,true,'Keluar…');try{await apiPost('logout',{},token)}catch{}finally{Auth.clearSession();location.replace(Utils.pageUrl('login.html'))}}
  return{init,logout,closeDrawer};
})();
document.querySelector('[data-admin-logout]')?.addEventListener('click',e=>AdminPage.logout(e.currentTarget));document.querySelector('[data-drawer]')?.addEventListener('click',()=>{document.querySelector('#admin-sidebar').classList.toggle('open');document.querySelector('[data-backdrop]').hidden=!document.querySelector('#admin-sidebar').classList.contains('open')});document.querySelector('[data-backdrop]')?.addEventListener('click',AdminPage.closeDrawer);AdminPage.init();
