const AdminPage=(()=>{
  let token="",candidate=null,winner=null,reward=null;
  async function init(){const session=Auth.requireLogin();if(!session)return;token=session.token;try{const result=await apiPost("getProfile",{},token),user=result.data;if(user.Role!=="ADMIN"&&user.Role!=="SUPERADMIN"){location.replace(Utils.pageUrl("app.html",{reason:"forbidden"}));return}Utils.setText("[data-admin-name]",user.Name);Utils.setText("[data-admin-role]",user.Role);document.querySelector("#admin-loading").hidden=true;document.querySelector("#admin-content").hidden=false}catch(error){document.querySelector("#admin-loading").textContent=Utils.errorMessage(error)}}
  const seasonId=()=>document.querySelector("[data-winner-season]").value.trim(),reason=()=>document.querySelector("[data-winner-reason]").value.trim();
  async function preview(){await act(async()=>{const response=await apiPost("adminPrepareSeasonFinalization",{seasonId:seasonId()},token),data=response.data;candidate=data.candidate;renderPreview(data);return response.message})}
  function renderPreview(data){const node=document.querySelector("[data-winner-preview-card]");node.hidden=false;if(!data.candidate){node.textContent="Tidak ada peserta yang memenuhi syarat.";return}node.replaceChildren();const title=document.createElement("h2"),details=document.createElement("p"),fraud=document.createElement("strong");title.textContent=`Kandidat #${data.candidate.rank} · ${data.candidate.name}`;details.textContent=`${data.candidate.schoolName} · ${data.candidate.point} Point · ${data.candidate.correctAnswers} benar · Average ${data.candidate.averageScore}`;fraud.textContent=`Status: ${data.status} · Fraud: ${data.candidate.fraudStatus}`;node.append(title,details,fraud)}
  async function disqualify(){if(!candidate)return setStatus("Muat kandidat terlebih dahulu.",true);await act(async()=>{const response=await apiPost("adminDisqualifyCandidate",{seasonId:seasonId(),userId:candidate.userId,reason:reason()},token);candidate=response.data.next.candidate;renderPreview(response.data.next);return response.message})}
  async function finalize(){if(!candidate)return setStatus("Muat kandidat terlebih dahulu.",true);if(!confirm(`Tetapkan ${candidate.name} sebagai pemenang? Tindakan ini dicatat dalam audit log.`))return;await act(async()=>{const response=await apiPost("adminFinalizeWinner",{seasonId:seasonId(),userId:candidate.userId,reason:reason()},token);winner=response.data.winner;reward=response.data.reward;document.querySelector("[data-winner-workflow]").hidden=false;return response.message})}
  async function verify(){await act(async()=>{const destination=prompt("Nomor tujuan hadiah:","")||"";const response=await apiPost("adminVerifyWinner",{winnerId:winner?.winnerId,seasonId:seasonId(),destinationNumber:destination,notes:reason()},token);winner=response.data.winner;reward=response.data.reward;return response.message})}
  async function rewardStatus(status){await act(async()=>{const response=await apiPost("adminUpdateRewardStatus",{rewardId:reward?.RewardID||reward?.rewardId,status,notes:reason()},token);reward=response.data;return response.message})}
  async function publish(){await act(async()=>{const response=await apiPost("adminPublishWinner",{winnerId:winner?.winnerId,seasonId:seasonId()},token);return response.message})}
  async function act(callback){try{setStatus("Memproses…");setStatus(await callback())}catch(error){setStatus(Utils.errorMessage(error),true)}}function setStatus(message,error){const node=document.querySelector("[data-winner-status]");node.textContent=message;node.className=error?"text-danger":"text-success"}
  async function logout(button){Utils.setButtonLoading(button,true,"Keluar…");try{if(token)await apiPost("logout",{},token)}catch{}finally{Auth.clearSession();location.replace(Utils.pageUrl("login.html"))}}
  return Object.freeze({init,preview,disqualify,finalize,verify,rewardStatus,publish,logout});
})();
document.querySelector("[data-winner-preview]")?.addEventListener("click",AdminPage.preview);document.querySelector("[data-winner-disqualify]")?.addEventListener("click",AdminPage.disqualify);document.querySelector("[data-winner-finalize]")?.addEventListener("click",AdminPage.finalize);document.querySelector("[data-winner-verify]")?.addEventListener("click",AdminPage.verify);document.querySelector("[data-reward-sent]")?.addEventListener("click",()=>AdminPage.rewardStatus("SENT"));document.querySelector("[data-reward-complete]")?.addEventListener("click",()=>AdminPage.rewardStatus("COMPLETED"));document.querySelector("[data-winner-publish]")?.addEventListener("click",AdminPage.publish);document.querySelector("[data-admin-logout]")?.addEventListener("click",event=>AdminPage.logout(event.currentTarget));AdminPage.init();
