const LeaderboardPage=(()=>{
  let seasonId=new URLSearchParams(location.search).get("seasonId")||"",mode="participant";
  async function init(){const session=Auth.getSession(),rankCard=document.querySelector("[data-my-rank-card]");rankCard.hidden=true;rankCard.style.display="none";if(session)document.querySelector("[data-leaderboard-home]").href="app.html";try{const seasonsResult=await apiGet("getLeaderboardSeasons"),seasons=seasonsResult.data||[],select=document.querySelector("[data-season-filter]");select.replaceChildren();seasons.forEach(season=>{const option=document.createElement("option");option.value=season.seasonId;option.textContent=season.name;select.append(option)});if(!seasons.length){select.disabled=true;renderRows([],false);return}if(!seasonId||!seasons.some(season=>season.seasonId===seasonId))seasonId=seasons[0].seasonId;select.value=seasonId;select.addEventListener("change",async()=>{seasonId=select.value;await load();if(session)await loadMyRank(session.token)});await load();if(session)await loadMyRank(session.token)}catch(error){showError(error)}}
  async function load(){setLoading(true);try{if(mode==="participant"){const response=await apiGet("getLeaderboard",{seasonId,limit:100,offset:0});renderParticipant(response.data)}else{const response=await apiGet("getSchoolLeaderboard",{seasonId,limit:100,offset:0});renderSchool(response.data)}}catch(error){showError(error)}}
  async function loadMyRank(token){const response=await apiPost("getMyRank",{seasonId},token);renderMyRank(response.data)}
  function renderMyRank(data){const card=document.querySelector("[data-my-rank-card]");Utils.setText("[data-my-rank-value]",data.rank?`#${data.rank}`:"Belum masuk ranking");Utils.setText("[data-my-rank-point]",`${new Intl.NumberFormat("id-ID").format(Number(data.seasonPoint||0))} POINT`);Utils.setText("[data-my-rank-total]",`Dari ${Number(data.totalParticipants||0)} peserta`);card.hidden=false;card.style.display="grid"}
  function renderParticipant(data){Utils.setText("[data-leaderboard-season]",data.season?.name||"Ranking Season");renderRows(data.entries||[],false)}
  function renderSchool(data){Utils.setText("[data-leaderboard-season]",data.season?.name||"Ranking Sekolah");renderRows(data.entries||[],true)}
  function renderRows(entries,isSchool){setLoading(false);const podium=document.querySelector("[data-podium]"),list=document.querySelector("[data-ranking-list]"),empty=document.querySelector("[data-leaderboard-empty]");podium.replaceChildren();list.replaceChildren();empty.hidden=entries.length>0;if(!entries.length)return;entries.slice(0,3).forEach((entry,index)=>podium.append(makeEntry(entry,isSchool,true,index)));entries.slice(3).forEach(entry=>list.append(makeEntry(entry,isSchool,false)))}
  function makeEntry(entry,isSchool,podium,index){const article=document.createElement("article");article.className=podium?`podium-card podium-${index+1}`:"ranking-row";const rank=document.createElement("strong"),body=document.createElement("div"),point=document.createElement("b");rank.className="ranking-number";rank.textContent=podium?["🥇 #1","🥈 #2","🥉 #3"][index]:`#${entry.rank}`;const name=document.createElement("strong"),meta=document.createElement("small");name.textContent=isSchool?entry.schoolName:entry.name;meta.textContent=isSchool?`${entry.participants} peserta · rata-rata ${entry.averagePoint}`:entry.schoolName||"Sekolah tidak tersedia";point.textContent=`${new Intl.NumberFormat("id-ID").format(Number(isSchool?entry.totalPoint:entry.point))} Point`;body.append(name,meta);article.append(rank,body,point);return article}
  function setLoading(value){document.querySelector("[data-board-loading]").hidden=!value;document.querySelector("[data-board-content]").hidden=value}
  function showError(error){setLoading(false);const empty=document.querySelector("[data-leaderboard-empty]");empty.hidden=false;empty.querySelector("h2").textContent="Leaderboard belum dapat dimuat";empty.querySelector("p").textContent=Utils.errorMessage(error)}
  function switchMode(next,button){mode=next;document.querySelectorAll("[data-board-tab]").forEach(node=>{node.classList.toggle("button-primary",node===button);node.classList.toggle("button-ghost",node!==button)});load()}
  return Object.freeze({init,switchMode});
})();
document.querySelectorAll("[data-board-tab]").forEach(button=>button.addEventListener("click",()=>LeaderboardPage.switchMode(button.dataset.boardTab,button)));LeaderboardPage.init();
