const PrivatePage=(()=>{
  function renderProfile(profile){const values={...profile,School:profile.School?.SchoolName||"—",BirthDate:Utils.formatDate(profile.BirthDate),TotalPoint:new Intl.NumberFormat("id-ID").format(Number(profile.TotalPoint||0))};document.querySelectorAll("[data-profile]").forEach(node=>node.textContent=values[node.dataset.profile]??"—");document.querySelector("#profile-loading")?.setAttribute("hidden","");document.querySelector("#dashboard-content")?.removeAttribute("hidden")}
  function renderSeason(season){const container=document.querySelector("[data-season-container]");if(!container)return;if(!season){container.innerHTML='<p class="eyebrow">CHALLENGE BULAN INI</p><h2>Belum ada season aktif</h2><p class="muted">Challenge berikutnya sedang dipersiapkan. Silakan kembali lagi nanti.</p>';return}container.innerHTML=`<p class="eyebrow">CHALLENGE AKTIF</p><h2>${escapeHtml(season.Name)}</h2><p class="season-theme">${escapeHtml(season.Theme||"")}</p><div class="season-meta"><span>${Utils.formatDate(season.StartDate)} – ${Utils.formatDate(season.EndDate)}</span><span>${Number(season.QuestionCount||0)} soal</span><span>Reward: ${escapeHtml(season.Reward||"—")}</span></div>`}
  function escapeHtml(value){const node=document.createElement("span");node.textContent=String(value);return node.innerHTML}
  async function init(){const session=Auth.requireLogin();if(!session)return;try{const profile=await apiPost("getProfile",{},session.token);renderProfile(profile.data)}catch(error){document.querySelector("#profile-loading").textContent=Utils.errorMessage(error);Utils.toast(Utils.errorMessage(error),"error");return}try{const season=await apiGet("getActiveSeason");renderSeason(season.data)}catch(error){renderSeason(null);if(CONFIG.DEBUG)console.warn("Season dashboard gagal",error.code)}}
  async function logout(button){const session=Auth.getSession();Utils.setButtonLoading(button,true,"Keluar…");try{if(session)await apiPost("logout",{},session.token)}catch(error){if(CONFIG.DEBUG)console.warn("Logout server gagal",error.code)}finally{Auth.clearSession();location.replace(Utils.pageUrl("login.html"))}}
  return Object.freeze({init,logout});
})();
document.querySelectorAll("[data-logout]").forEach(button=>button.addEventListener("click",()=>PrivatePage.logout(button)));PrivatePage.init();
if(CONFIG.DEBUG)checkApiHealth().catch(()=>{});
