const PrivatePage=(()=>{
  function renderProfile(profile){const values={...profile,School:profile.School?.SchoolName||"—",BirthDate:Utils.formatDate(profile.BirthDate),TotalPoint:new Intl.NumberFormat("id-ID").format(Number(profile.TotalPoint||0))};document.querySelectorAll("[data-profile]").forEach(node=>node.textContent=values[node.dataset.profile]??"—");document.querySelector("#profile-loading")?.setAttribute("hidden","");document.querySelector("#dashboard-content")?.removeAttribute("hidden")}
  function renderSeason(season,status){const container=document.querySelector("[data-season-container]");if(!container)return;if(!season){container.innerHTML='<p class="eyebrow">CHALLENGE BULAN INI</p><h2>Belum ada season aktif</h2><p class="muted">Challenge berikutnya sedang dipersiapkan. Silakan kembali lagi nanti.</p>';return}let label="MULAI CHALLENGE",disabled=false;if(status?.canResume)label="LANJUTKAN CHALLENGE";else if(status?.completed&&!status?.canStart){label="CHALLENGE SELESAI ✓";disabled=true}else if(!status?.canStart){label="CHALLENGE TIDAK TERSEDIA";disabled=true}container.innerHTML=`<p class="eyebrow">CHALLENGE AKTIF</p><h2>${escapeHtml(season.Name)}</h2><p class="season-theme">${escapeHtml(season.Theme||"")}</p><div class="season-meta"><span>${Utils.formatDate(season.StartDate)} – ${Utils.formatDate(season.EndDate)}</span><span>${Number(season.QuestionCount||0)} soal</span><span>Reward: ${escapeHtml(season.Reward||"—")}</span></div><button class="button button-primary challenge-cta" type="button" ${disabled?"disabled":""}>${label}</button>`;container.querySelector(".challenge-cta")?.addEventListener("click",()=>location.assign(Utils.pageUrl("quiz.html",{seasonId:season.SeasonID})))}
  function escapeHtml(value){const node=document.createElement("span");node.textContent=String(value);return node.innerHTML}
  async function init(){const session=Auth.requireLogin();if(!session)return;if(new URLSearchParams(location.search).get("reason")==="forbidden")Utils.toast("Akses ditolak. Halaman tersebut hanya untuk administrator.","error");try{const profile=await apiPost("getProfile",{},session.token);renderProfile(profile.data)}catch(error){document.querySelector("#profile-loading").textContent=Utils.errorMessage(error);Utils.toast(Utils.errorMessage(error),"error");return}const container=document.querySelector("[data-season-container]");if(!container)return;let season=null;try{const seasonResult=await apiGet("getActiveSeason");season=seasonResult.data;if(!season){renderSeason(null);return}renderSeason(season,{canStart:false});const [status,stats]=await Promise.all([apiPost("getQuizStatus",{seasonId:season.SeasonID},session.token),apiPost("getMySeasonStats",{seasonId:season.SeasonID},session.token)]);renderSeason(season,status.data);Utils.setText('[data-profile="TotalPoint"]',new Intl.NumberFormat("id-ID").format(Number(stats.data.seasonPoint||0)))}catch(error){renderSeason(season,{canStart:false});Utils.toast(Utils.errorMessage(error),"error");if(CONFIG.DEBUG)console.warn("Season dashboard gagal",error.code)}}
  async function logout(button){const session=Auth.getSession();Utils.setButtonLoading(button,true,"Keluar…");try{if(session)await apiPost("logout",{},session.token)}catch(error){if(CONFIG.DEBUG)console.warn("Logout server gagal",error.code)}finally{Auth.clearSession();location.replace(Utils.pageUrl("login.html"))}}
  return Object.freeze({init,logout});
})();
document.querySelectorAll("[data-logout]").forEach(button=>button.addEventListener("click",()=>PrivatePage.logout(button)));PrivatePage.init();
if(CONFIG.DEBUG)checkApiHealth().catch(()=>{});
