const QuizPage=(()=>{
  let token="",seasonId="",quizSessionId="",currentQuestion=null,timerId=null,remaining=0;
  async function init(){const session=Auth.requireLogin();if(!session)return;token=session.token;seasonId=new URLSearchParams(location.search).get("seasonId")||"";try{const status=await apiPost("getQuizStatus",{seasonId},token);seasonId=status.data.season.SeasonID;if(status.data.completed&&!status.data.canStart&&!status.data.canResume&&status.data.completedSessionId){const result=await apiPost("getQuizResult",{quizSessionId:status.data.completedSessionId},token);renderResult(result.data);return}const started=await apiPost("startQuiz",{seasonId},token);quizSessionId=started.data.quizSessionId;renderSession(started.data)}catch(error){showFatal(error)}}
  function renderSession(data){document.querySelector("#quiz-loading")?.setAttribute("hidden","");document.querySelector("#quiz-screen")?.removeAttribute("hidden");Utils.setText("[data-season-name]",data.season.Name);quizSessionId=data.quizSessionId;startTimer(data.remainingSeconds,Number(data.season.QuizDuration||0));if(!data.question){showFatal({code:"QUIZ_NOT_AVAILABLE",message:"Tidak ada pertanyaan berikutnya."});return}renderQuestion(data.question)}
  function renderQuestion(question){currentQuestion=question;Utils.setText("[data-question-count]",`SOAL ${question.index} / ${question.total}`);Utils.setText("[data-progress-percent]",`${Math.round((question.index-1)/question.total*100)}%`);document.querySelector("[data-progress-bar]").style.width=`${(question.index-1)/question.total*100}%`;Utils.setText("[data-question-text]",question.question);const options=document.querySelector("[data-answer-options]");options.replaceChildren();question.options.forEach((option,index)=>{const label=document.createElement("label");label.className="answer-option";const input=document.createElement("input");input.type="radio";input.name="selectedOption";input.value=option.id;const marker=document.createElement("span");marker.className="answer-marker";marker.textContent=String.fromCharCode(65+index);const text=document.createElement("span");text.textContent=option.text;label.append(input,marker,text);options.append(label)});const submit=document.querySelector("#answer-form button[type=submit]");submit.disabled=true;options.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>submit.disabled=false));document.querySelector("[data-answer-feedback]").hidden=true;document.querySelector("[data-next-question]").hidden=true;submit.hidden=false}
  async function submit(event){event.preventDefault();const button=event.currentTarget.querySelector("button[type=submit]"),selected=event.currentTarget.querySelector("input[name=selectedOption]:checked");if(!selected||!currentQuestion)return;Utils.setButtonLoading(button,true,"Mengirim…");event.currentTarget.querySelectorAll("input").forEach(input=>input.disabled=true);try{const response=await apiPost("submitAnswer",{quizSessionId,questionId:currentQuestion.questionId,selectedOption:selected.value},token),data=response.data;if(data.completed){renderResult(data.result);return}renderFeedback(data);button.hidden=true;const next=document.querySelector("[data-next-question]");next.hidden=false}catch(error){Utils.toast(Utils.errorMessage(error),"error");event.currentTarget.querySelectorAll("input").forEach(input=>input.disabled=false);Utils.setButtonLoading(button,false)} }
  function renderFeedback(data){const node=document.querySelector("[data-answer-feedback]");node.hidden=false;if(typeof data.isCorrect==="boolean"){node.className=`answer-feedback ${data.isCorrect?"feedback-correct":"feedback-wrong"}`;node.innerHTML=`<strong>${data.isCorrect?"BENAR":"BELUM TEPAT"}${data.point?` · +${Number(data.point)} POINT`:""}</strong>${data.correctAnswer?`<p>Jawaban: ${escapeHtml(data.correctAnswer)}</p>`:""}${data.explanation?`<p>${escapeHtml(data.explanation)}</p>`:""}`}else{node.className="answer-feedback feedback-accepted";node.innerHTML=`<strong>JAWABAN DITERIMA${data.point?` · +${Number(data.point)} POINT`:""}</strong>`}}
  async function next(){const button=document.querySelector("[data-next-question]");Utils.setButtonLoading(button,true,"Memuat…");try{const response=await apiPost("getCurrentQuestion",{quizSessionId},token);renderSession(response.data)}catch(error){showFatal(error)}finally{Utils.setButtonLoading(button,false)}}
  function renderResult(result){clearInterval(timerId);document.querySelector("#quiz-loading")?.setAttribute("hidden","");document.querySelector("#quiz-screen")?.setAttribute("hidden","");document.querySelector("#quiz-result")?.removeAttribute("hidden");Utils.setText("[data-result-correct]",result.correct);Utils.setText("[data-result-wrong]",result.wrong);Utils.setText("[data-result-score]",result.score);Utils.setText("[data-result-point]",`+${Number(result.point||0)}`);Utils.setText("[data-result-total]",new Intl.NumberFormat("id-ID").format(Number(result.totalPoint||0)))}
  function startTimer(seconds,duration){const node=document.querySelector("[data-quiz-timer]");clearInterval(timerId);if(duration<=0){node.hidden=true;return}remaining=Math.max(0,Number(seconds));node.hidden=false;renderTimer(node);timerId=setInterval(()=>{remaining=Math.max(0,remaining-1);renderTimer(node);if(remaining===0){clearInterval(timerId);Utils.toast("Waktu habis. Server akan memvalidasi status quiz.","error")}},1000)}
  function renderTimer(node){const minutes=Math.floor(remaining/60),seconds=remaining%60;node.textContent=`${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`;node.classList.toggle("timer-warning",remaining<=60)}
  function showFatal(error){clearInterval(timerId);document.querySelector("#quiz-screen")?.setAttribute("hidden","");const loading=document.querySelector("#quiz-loading");loading.removeAttribute("hidden");loading.classList.remove("skeleton-card");loading.innerHTML=`<p class="eyebrow">QUIZ</p><h1>Challenge tidak dapat dibuka</h1><p>${escapeHtml(Utils.errorMessage(error))}</p><a class="button button-primary" href="app.html">Kembali ke dashboard</a>`}
  function escapeHtml(value){const node=document.createElement("span");node.textContent=String(value??"");return node.innerHTML}
  return Object.freeze({init,submit,next});
})();
document.querySelector("#answer-form")?.addEventListener("submit",QuizPage.submit);document.querySelector("[data-next-question]")?.addEventListener("click",QuizPage.next);QuizPage.init();
