const Utils=Object.freeze({
  isConfiguredApi(){return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/.test(CONFIG.API_URL)},
  pageUrl(page="",params={}){const base=CONFIG.BASE_PATH.endsWith("/")?CONFIG.BASE_PATH:`${CONFIG.BASE_PATH}/`;const query=new URLSearchParams(params).toString();return `${base}${page}${query?`?${query}`:""}`},
  setText(selector,value){const node=document.querySelector(selector);if(node)node.textContent=value??"—"},
  formObject(form){return Object.fromEntries(new FormData(form).entries())},
  formatDate(value){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(date)},
  isProductionContent(value){const text=typeof value==="string"?value:JSON.stringify(value??"");return !/(?:^|[_\s-])(?:demo|dummy|test)(?:$|[_\s-])|lorem ipsum/i.test(text)},
  setButtonLoading(button,loading,label="Memproses…"){if(!button)return;if(loading){button.dataset.label=button.textContent;button.disabled=true;button.innerHTML=`<span class="spinner" aria-hidden="true"></span>${label}`}else{button.disabled=false;button.textContent=button.dataset.label||button.textContent}},
  toast(message,type="info"){let region=document.querySelector(".toast-region");if(!region){region=document.createElement("div");region.className="toast-region";region.setAttribute("aria-live","polite");document.body.append(region)}const toast=document.createElement("div");toast.className=`toast toast-${type}`;toast.textContent=message;region.append(toast);requestAnimationFrame(()=>toast.classList.add("toast-visible"));setTimeout(()=>{toast.classList.remove("toast-visible");setTimeout(()=>toast.remove(),250)},4500)},
  errorMessage(error){const messages={DUPLICATE_NIS:"NIS/NISN sudah terdaftar.",DUPLICATE_EMAIL:"Email sudah digunakan.",SCHOOL_NOT_FOUND:"Sekolah tidak ditemukan atau sudah tidak aktif.",REGISTRATION_CLOSED:"Pendaftaran sedang ditutup.",VALIDATION_ERROR:error.message||"Data yang dimasukkan belum valid.",INVALID_CREDENTIALS:"Email/NIS atau password salah.",USER_BLOCKED:"Akun diblokir. Hubungi administrator.",USER_SUSPENDED:"Akun ditangguhkan. Hubungi administrator.",SESSION_INVALID:"Sesi Anda telah berakhir. Silakan masuk kembali.",SESSION_EXPIRED:"Sesi Anda telah berakhir. Silakan masuk kembali.",NETWORK_ERROR:"Layanan belum dapat dihubungi. Periksa koneksi internet.",RATE_LIMITED:"Terlalu banyak percobaan. Tunggu beberapa menit.",NO_ACTIVE_SEASON:"Belum ada season aktif.",SEASON_NOT_STARTED:"Season belum dimulai.",SEASON_ENDED:"Season telah berakhir.",QUIZ_NOT_AVAILABLE:"Challenge belum tersedia.",MAX_ATTEMPT_REACHED:"Batas percobaan challenge telah tercapai.",QUIZ_SESSION_NOT_FOUND:"Sesi challenge tidak ditemukan.",QUIZ_SESSION_EXPIRED:"Waktu challenge telah berakhir.",QUIZ_ALREADY_COMPLETED:"Challenge sudah selesai.",QUIZ_ALREADY_SUBMITTED:"Jawaban challenge sudah pernah dikirim.",QUESTION_NOT_FOUND:"Pertanyaan tidak ditemukan.",QUESTION_NOT_IN_SESSION:"Pertanyaan bukan bagian dari challenge ini.",QUESTION_ALREADY_ANSWERED:"Pertanyaan ini sudah dijawab.",DUPLICATE_ANSWER:"Satu pertanyaan dikirim lebih dari sekali.",INVALID_OPTION:"Pilihan jawaban tidak valid.",INSUFFICIENT_QUESTIONS:"Jumlah soal aktif belum mencukupi. Hubungi administrator."};return messages[error.code]||error.message||"Terjadi kesalahan."}
});
