const assert=require('assert');const fs=require('fs');const vm=require('vm');
const storage=new Map(),requests=[];let response={success:true,message:'API healthy',data:{database:true}};const location={replaced:'',replace(value){this.replaced=value},assign(value){this.replaced=value}};
const context={console,URLSearchParams,AbortController,setTimeout,clearTimeout,Intl,Date,Error,JSON,Object,String,Number,RegExp,Map,location,navigator:{onLine:true},sessionStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null,removeItem:k=>storage.delete(k)},document:{body:{dataset:{page:'test'}},querySelector(){return null},querySelectorAll(){return[]},createElement(){return{dataset:{},classList:{add(){},remove(){}},setAttribute(){},append(){},remove(){},textContent:'',get innerHTML(){return this.textContent}}}},requestAnimationFrame:fn=>fn(),fetch:async(url,options)=>{requests.push({url:String(url),options});return{ok:true,status:200,json:async()=>response}}};vm.createContext(context);
function run(file,transform=value=>value){vm.runInContext(transform(fs.readFileSync(file,'utf8')),context,{filename:file});}
run('js/config.js',source=>source.replace('GOOGLE_APPS_SCRIPT_WEB_APP_DEPLOYMENT_URL','https://script.google.com/macros/s/test-deployment/exec'));
run('js/utils.js');run('js/api.js');run('js/auth.js');
(async()=>{
  const health=await vm.runInContext('apiGet("health")',context);assert.equal(health.data.database,true);assert.match(requests[0].url,/action=health/);assert.equal(requests[0].options.method,'GET');assert.equal(requests[0].options.headers,undefined);assert.equal(requests[0].options.redirect,'follow');
  response={success:true,message:'Registrasi berhasil.',data:{UserID:'USR_1'}};await vm.runInContext('apiPost("register",{name:"Siti",nis:"12345"})',context);const post=requests[1];assert.equal(post.options.method,'POST');assert.equal(post.options.headers['Content-Type'],'application/x-www-form-urlencoded;charset=UTF-8');assert.equal(post.options.redirect,'follow');assert.equal(post.options.body.get('action'),'register');assert.deepEqual(JSON.parse(post.options.body.get('payload')),{name:'Siti',nis:'12345'});assert.equal(post.options.body.has('token'),false);
  vm.runInContext('Auth.saveSession({token:"secret-token",expiresAt:new Date(Date.now()+60000).toISOString()})',context);assert.equal(vm.runInContext('Auth.isLoggedIn()',context),true);assert.equal(JSON.parse(storage.get('pemilih_muda_session_v1')).token,'secret-token');assert.equal(storage.get('pemilih_muda_session_v1').includes('password'),false);
  response={success:false,message:'Sesi berakhir.',code:'SESSION_EXPIRED'};let code='';try{await vm.runInContext('apiPost("getProfile",{},Auth.getSession().token)',context)}catch(error){code=error.code}assert.equal(code,'SESSION_EXPIRED');assert.equal(storage.has('pemilih_muda_session_v1'),false);assert.match(location.replaced,/\/pemilih-muda\/login\.html\?reason=session_expired/);
  assert.equal(vm.runInContext('Utils.pageUrl("app.html")',context),'/pemilih-muda/app.html');console.log('Phase 4 frontend integration tests passed.');
})().catch(error=>{console.error(error);process.exitCode=1});
