const assert=require('assert');const crypto=require('crypto');const fs=require('fs');const path=require('path');const vm=require('vm');
class Range{constructor(sheet,row,col,rows,cols){Object.assign(this,{sheet,row,col,rows,cols});}getValues(){const out=[];for(let r=0;r<this.rows;r++){const line=[];for(let c=0;c<this.cols;c++)line.push(this.sheet.cells[this.row-1+r]?.[this.col-1+c]??'');out.push(line);}return out;}setValues(values){for(let r=0;r<this.rows;r++){this.sheet.cells[this.row-1+r]??=[];for(let c=0;c<this.cols;c++)this.sheet.cells[this.row-1+r][this.col-1+c]=values[r][c];}return this;}clearContent(){for(let r=0;r<this.rows;r++)for(let c=0;c<this.cols;c++)if(this.sheet.cells[this.row-1+r])this.sheet.cells[this.row-1+r][this.col-1+c]='';return this;}}
class Sheet{constructor(name){this.name=name;this.cells=[];}getName(){return this.name;}getLastRow(){let last=0;this.cells.forEach((row,i)=>{if(row.some(v=>v!==''&&v!==undefined))last=i+1;});return last;}getLastColumn(){let last=0;this.cells.forEach(row=>row.forEach((v,i)=>{if(v!==''&&v!==undefined)last=Math.max(last,i+1);}));return last;}getRange(r,c,rows=1,cols=1){return new Range(this,r,c,rows,cols);}getDataRange(){return this.getRange(1,1,Math.max(this.getLastRow(),1),Math.max(this.getLastColumn(),1));}setFrozenRows(){} }
class Spreadsheet{constructor(id){this.id=id;this.sheets=[new Sheet('Sheet1')];}getId(){return this.id;}getSheetByName(name){return this.sheets.find(s=>s.name===name)||null;}insertSheet(name){const s=new Sheet(name);this.sheets.push(s);return s;}getSheets(){return this.sheets;}deleteSheet(sheet){this.sheets=this.sheets.filter(s=>s!==sheet);}}
const propertyData={};const books={};let uuidCounter=0;const lock={waitLock(){},releaseLock(){}};
const cacheData={};const context={console,Date,JSON,Object,String,Number,RegExp,Error,Math,Logger:{log(){}},PropertiesService:{getScriptProperties(){return{getProperty:k=>propertyData[k]||null,setProperty:(k,v)=>propertyData[k]=String(v),deleteProperty:k=>delete propertyData[k]};}},SpreadsheetApp:{create(){const id='db-'+Object.keys(books).length;return books[id]=new Spreadsheet(id);},openById(id){if(!books[id])throw Error('not found');return books[id];}},LockService:{getScriptLock:()=>lock},CacheService:{getScriptCache(){return{get:k=>cacheData[k]||null,put:(k,v)=>cacheData[k]=v};}},Utilities:{Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},getUuid(){return (++uuidCounter).toString(16).padEnd(32,'0').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5');},computeDigest(algorithm,value){const input=Array.isArray(value)?Buffer.from(value.map(v=>v<0?v+256:v)):Buffer.from(String(value),'utf8');return [...crypto.createHash(algorithm).update(input).digest()].map(v=>v>127?v-256:v);}},ContentService:{MimeType:{JSON:'json'},createTextOutput(value){return{value,setMimeType(){return this;}}}}};vm.createContext(context);
const order=['Config.gs','Schema.gs','Utility.gs','ValidationService.gs','SecurityService.gs','DatabaseService.gs','SetupService.gs','DemoDataService.gs','SessionService.gs','AuthService.gs','SchoolService.gs','ApiService.gs','AdminService.gs','Router.gs'];for(const file of order)vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas-backend',file),'utf8'),context,{filename:file});
propertyData.INITIAL_ADMIN_NAME='Admin Demo';propertyData.INITIAL_ADMIN_EMAIL='admin@example.test';propertyData.INITIAL_ADMIN_PASSWORD='SangatRahasia123!';
const first=context.setupApplication();assert.equal(first.success,true);assert.equal(first.createdSheets.length,17);assert.equal(first.createdSettings.length,14);assert.ok(propertyData.DATABASE_SPREADSHEET_ID);assert.equal(propertyData.INITIAL_ADMIN_PASSWORD,undefined);assert.equal(context.DatabaseService.getAllRows('Users').length,1);assert.notEqual(context.DatabaseService.getAllRows('Users')[0].PasswordHash,'SangatRahasia123!');
const firstId=first.spreadsheetId;const second=context.setupApplication();assert.equal(second.success,true);assert.equal(second.spreadsheetId,firstId);assert.equal(second.createdSheets.length,0);assert.equal(second.createdSettings.length,0);assert.equal(context.DatabaseService.getAllRows('Users').length,1);
const seeded=context.seedDemoData();assert.deepEqual(JSON.parse(JSON.stringify(seeded.created)),{Schools:5,Questions:30,Seasons:1,Materials:5,Announcements:3});const reseeded=context.seedDemoData();assert.ok(Object.values(reseeded.created).every(v=>v===0));assert.equal(context.validateDatabaseSchema().valid,true);
context.DatabaseService.insert('Schools',{SchoolID:'SCH_production01',SchoolName:'Production'});const cleared=context.clearDemoData();assert.equal(cleared.removed.Questions,30);assert.equal(context.DatabaseService.getAllRows('Schools').length,1);assert.equal(context.DatabaseService.getAllRows('Schools')[0].SchoolID,'SCH_production01');
const salt=context.generateSalt(),hash=context.hashPassword('password-ku',salt);assert.equal(context.verifyPassword('password-ku',salt,hash),true);assert.equal(context.verifyPassword('salah',salt,hash),false);console.log('Phase 2 tests passed.');
function call(method,action,payload={},token=''){const e={parameter:{action,payload:JSON.stringify(payload),token},postData:{type:'application/x-www-form-urlencoded',contents:''}};return JSON.parse(context.routeRequest_(method,e).value);}
const health=call('GET','health');assert.equal(health.success,true);assert.equal(health.data.database,true);
const adminLogin=call('POST','login',{identifier:'admin@example.test',password:'SangatRahasia123!'});assert.equal(adminLogin.success,true);assert.ok(adminLogin.data.token);assert.equal(JSON.stringify(adminLogin).includes('PasswordHash'),false);const adminToken=adminLogin.data.token;
const school=call('POST','adminCreateSchool',{schoolName:'SMAN API Test',npsn:'99123456',type:'SMA',district:'Test'},adminToken);assert.equal(school.success,true);
const registration=call('POST','register',{name:'Siswa Test',nis:'1234567890',schoolId:school.data.SchoolID,class:'XII',birthDate:'2008-01-02',whatsapp:'081234567890',email:'siswa@example.test',password:'Rahasia123!'});assert.equal(registration.success,true);assert.equal(registration.data.Role,'STUDENT');
const duplicate=call('POST','register',{name:'Duplikat',nis:'1234567890',schoolId:school.data.SchoolID,class:'XII',birthDate:'2008-01-02',whatsapp:'081234567890',email:'beda@example.test',password:'Rahasia123!'});assert.equal(duplicate.code,'DUPLICATE_NIS');
const studentLogin=call('POST','login',{identifier:'siswa@example.test',password:'Rahasia123!'});assert.equal(studentLogin.success,true);const studentToken=studentLogin.data.token;const profile=call('POST','getProfile',{},studentToken);assert.equal(profile.success,true);assert.equal(Object.prototype.hasOwnProperty.call(profile.data,'FraudScore'),false);assert.equal(JSON.stringify(profile).includes('PasswordSalt'),false);
const forbidden=call('POST','adminGetUsers',{},studentToken);assert.equal(forbidden.code,'FORBIDDEN',JSON.stringify(forbidden));const users=call('POST','adminGetUsers',{},adminToken);assert.equal(users.success,true);assert.equal(JSON.stringify(users).includes('PasswordHash'),false);
assert.equal(call('POST','logout',{},studentToken).success,true);assert.equal(call('POST','getProfile',{},studentToken).code,'SESSION_INVALID');assert.equal(call('GET','unknown').code,'API_ACTION_NOT_FOUND');console.log('Phase 3 API tests passed.');
