var ApiService=Object.freeze({
  health:function(){var database=false;try{database=Boolean(DatabaseService.getSpreadsheet().getSheetByName('Settings'));}catch(ignore){}return successResponse({app:APP_CONFIG.NAME,version:APP_CONFIG.VERSION,timestamp:nowIso_(),database:database},'API healthy');},
  getAppStatus:function(){return successResponse({appName:getSetting_('APP_NAME',APP_CONFIG.NAME),registrationOpen:Boolean(getSetting_('REGISTRATION_OPEN',true)),maintenanceMode:Boolean(getSetting_('MAINTENANCE_MODE',false))},'Status aplikasi berhasil dimuat.');},
  getActiveSeason:function(){var active=findPlayableSeasons_();if(active.length>1){console.error('Lebih dari satu season ACTIVE ditemukan.');logActivity_('','API_ERROR','Season','','MULTIPLE_ACTIVE_SEASONS','');}var row=active[0];return successResponse(row?publicSeason_(row,active.length>1?'MULTIPLE_ACTIVE_SEASONS':''):null,row?'Season aktif ditemukan.':'Tidak ada season aktif.');},
  getPublishedMaterials:function(){return successResponse(DatabaseService.getAllRows('Materials').filter(function(r){return r.Status==='PUBLISHED';}).map(function(r){return{MaterialID:r.MaterialID,Title:r.Title,Category:r.Category,Thumbnail:r.Thumbnail,Content:r.Content,VideoURL:r.VideoURL,PublishedAt:r.PublishedAt};}),'Materi berhasil dimuat.');},
  getPublishedAnnouncements:function(){var now=Date.now();return successResponse(DatabaseService.getAllRows('Announcements').filter(function(r){return r.Status==='ACTIVE'&&(!r.StartDate||new Date(r.StartDate).getTime()<=now)&&(!r.EndDate||new Date(r.EndDate).getTime()+86400000>now);}).map(function(r){return{AnnouncementID:r.AnnouncementID,Title:r.Title,Content:r.Content,Type:r.Type,StartDate:r.StartDate,EndDate:r.EndDate};}),'Pengumuman berhasil dimuat.');},
  getPublicLeaderboard:function(request){if(!getSetting_('SHOW_LEADERBOARD',true))return successResponse([],'Leaderboard dinonaktifkan.');var seasonId=sanitizeText_(request.payload.seasonId||request.identifier||'',40,'SeasonID');var totals={};DatabaseService.getAllRows('PointTransactions').filter(function(p){return p.Status==='VALID'&&(!seasonId||p.SeasonID===seasonId);}).forEach(function(p){totals[p.UserID]=(totals[p.UserID]||0)+Number(p.Point||0);});var users={};DatabaseService.getAllRows('Users').forEach(function(u){users[u.UserID]=u;});var schools={};DatabaseService.getAllRows('Schools').forEach(function(s){schools[s.SchoolID]=s.SchoolName;});var limit=Math.min(Math.max(Number(request.payload.limit||50),1),50);var rows=Object.keys(totals).filter(function(id){return users[id];}).map(function(id){return{name:maskName_(users[id].Name),school:schools[users[id].SchoolID]||'',point:totals[id]};}).sort(function(a,b){return b.point-a.point||a.name.localeCompare(b.name);}).slice(0,limit);rows.forEach(function(row,index){row.rank=index+1;});return successResponse(rows,'Leaderboard berhasil dimuat.');}
});
function maskName_(name){var parts=String(name).trim().split(/\s+/);return parts.map(function(part,index){return index===0?part:part.charAt(0)+'.';}).join(' ');}
function findPlayableSeasons_(){var now=Date.now();return DatabaseService.getAllRows('Seasons').filter(function(row){return row.Status==='ACTIVE'&&dateStart_(row.StartDate)<=now&&dateEnd_(row.EndDate)>=now;});}
function publicSeason_(row,warning){return{SeasonID:row.SeasonID,Name:row.Name,Theme:row.Theme,Description:row.Description,StartDate:row.StartDate,EndDate:row.EndDate,Reward:row.Reward,QuestionCount:Number(row.QuestionCount),PointPerQuestion:Number(row.PointPerQuestion),MaxAttempt:Number(row.MaxAttempt),QuizDuration:Number(row.QuizDuration),ShowExplanation:toBoolean_(row.ShowExplanation),warning:warning||undefined};}
function dateStart_(value){var date=value instanceof Date?new Date(value):new Date(String(value));date.setHours(0,0,0,0);return date.getTime();}
function dateEnd_(value){var date=value instanceof Date?new Date(value):new Date(String(value));date.setHours(23,59,59,999);return date.getTime();}
function toBoolean_(value){return value===true||String(value).toLowerCase()==='true';}
