var AuthService=(function(){
  function register(input,request){input=input||{};var identifier=sanitizeText_(input.email||input.nis||request.identifier,160,'identifier');rateLimit_('register',identifier||'unknown',10,300);return DatabaseService.withLock(function(){
    var name=rejectFormula_(input.name,120,'Nama');var nis=sanitizeText_(input.nis,20,'NIS');var schoolId=sanitizeText_(input.schoolId,40,'SchoolID');var studentClass=rejectFormula_(input['class'],40,'Kelas');var birthDate=sanitizeText_(input.birthDate,20,'Tanggal lahir');var whatsapp=sanitizeText_(input.whatsapp,24,'WhatsApp');var email=sanitizeText_(input.email,160,'Email').toLowerCase();var password=String(input.password||'');
    ValidationService.validateRequired(name,'Nama');ValidationService.validateNIS(nis);ValidationService.validateRequired(schoolId,'Sekolah');ValidationService.validateRequired(studentClass,'Kelas');ValidationService.validateDate(birthDate,'Tanggal lahir');ValidationService.validatePhone(whatsapp);ValidationService.validateEmail(email);if(password.length<8||password.length>128)throw new AppError('Password harus 8–128 karakter.','VALIDATION_ERROR');
    var school=DatabaseService.findById('Schools','SchoolID',schoolId);if(!school||school.Status!=='ACTIVE')throw new AppError('Sekolah tidak ditemukan.','SCHOOL_NOT_FOUND');if(DatabaseService.exists('Users','NIS',nis))throw new AppError('NIS/NISN sudah terdaftar.','DUPLICATE_NIS');if(findUserByEmail_(email))throw new AppError('Email sudah terdaftar.','DUPLICATE_EMAIL');if(!getSetting_('REGISTRATION_OPEN',true))throw new AppError('Registrasi sedang ditutup.','REGISTRATION_CLOSED');
    var salt=generateSalt(),now=nowIso_(),user={UserID:generateId('USR'),Name:name,NIS:nis,SchoolID:schoolId,Class:studentClass,BirthDate:birthDate,WhatsApp:whatsapp,Email:email,PasswordHash:hashPassword(password,salt),PasswordSalt:salt,Role:'STUDENT',Status:'ACTIVE',TotalPointCache:0,FraudScore:0,CreatedAt:now,UpdatedAt:now,LastLogin:''};DatabaseService.insert('Users',user);logActivity_(user.UserID,'REGISTER','User',user.UserID,'Registrasi peserta',request.userAgent);return successResponse(safeUser_(user),'Registrasi berhasil.');
  });}
  function login(input,request){input=input||{};var identifier=sanitizeText_(input.identifier||input.email||input.nis,160,'identifier').toLowerCase();rateLimit_('login',identifier||'unknown',10,300);var password=String(input.password||'');if(!identifier||!password)throw new AppError('Identifier dan password wajib diisi.','VALIDATION_ERROR');var user=identifier.indexOf('@')>=0?findUserByEmail_(identifier):DatabaseService.findOne('Users','NIS',identifier);if(!user){logActivity_('','LOGIN_FAILED','User','', 'User tidak ditemukan',request.userAgent);throw new AppError('Email/NIS atau password salah.','INVALID_CREDENTIALS');}if(user.Status==='BLOCKED')throw new AppError('Akun diblokir.','USER_BLOCKED');if(user.Status==='SUSPENDED')throw new AppError('Akun ditangguhkan.','USER_SUSPENDED');if(user.Status!=='ACTIVE')throw new AppError('Akun belum aktif.','UNAUTHORIZED');if(!verifyPassword(password,user.PasswordSalt,user.PasswordHash)){logActivity_(user.UserID,'LOGIN_FAILED','User',user.UserID,'Password tidak cocok',request.userAgent);throw new AppError('Email/NIS atau password salah.','INVALID_CREDENTIALS');}var session=SessionService.createSession(user,request);DatabaseService.updateById('Users','UserID',user.UserID,{LastLogin:nowIso_(),UpdatedAt:nowIso_()});logActivity_(user.UserID,'LOGIN','User',user.UserID,'Login berhasil',request.userAgent);return successResponse({token:session.token,expiresAt:session.expiresAt,user:safeUser_(user)},'Login berhasil.');}
  function logout(token,request){var auth=SessionService.revokeSession(token);logActivity_(auth.user.UserID,'LOGOUT','User',auth.user.UserID,'Logout berhasil',request.userAgent);return successResponse({},'Logout berhasil.');}
  function getProfile(token){var auth=requireAuth(token);var user=auth.user;var school=DatabaseService.findById('Schools','SchoolID',user.SchoolID);return successResponse({UserID:user.UserID,Name:user.Name,NIS:user.NIS,School:school?{SchoolID:school.SchoolID,SchoolName:school.SchoolName}:null,Class:user.Class,BirthDate:user.BirthDate,WhatsApp:user.WhatsApp,Email:user.Email,Role:user.Role,Status:user.Status,TotalPoint:Number(user.TotalPointCache||0)},'Profil berhasil dimuat.');}
  function findUserByEmail_(email){var normalized=String(email).toLowerCase();return DatabaseService.getAllRows('Users').filter(function(user){return String(user.Email).toLowerCase()===normalized;})[0]||null;}
  return Object.freeze({register:register,login:login,logout:logout,getProfile:getProfile});
})();
