var LEADERBOARD_CACHE_PREFIX='LEADERBOARD_V1_',LEADERBOARD_CACHE_TTL=180;
var LeaderboardService=(function(){
  function getLeaderboard(input){if(!getSetting_('SHOW_LEADERBOARD',true))return successResponse({season:null,totalParticipants:0,entries:[]},'Leaderboard dinonaktifkan.');input=input||{};var season=resolveLeaderboardSeason_(input.seasonId),snapshot=getSnapshot_(season.SeasonID),page=page_(snapshot.entries,input);return successResponse({season:publicLeaderboardSeason_(season),totalParticipants:snapshot.entries.length,entries:page.map(publicEntry_)},snapshot.entries.length?'Leaderboard berhasil dimuat.':'Leaderboard belum tersedia.');}
  function getMyRank(token,input){var auth=requireAuthFast(token),season=resolveLeaderboardSeason_(input&&input.seasonId),snapshot=getSnapshot_(season.SeasonID),entry=snapshot.entries.filter(function(row){return row.userId===auth.user.UserID;})[0]||null,top=snapshot.entries[0];return successResponse({season:publicLeaderboardSeason_(season),rank:entry?entry.rank:null,seasonPoint:entry?entry.point:seasonPointFromLedger_(auth.user.UserID,season.SeasonID),totalParticipants:snapshot.entries.length,distanceToTop:entry&&top?Math.max(0,top.point-entry.point):null},entry?'Ranking berhasil dimuat.':'Belum masuk ranking.');}
  function getSchoolLeaderboard(input){input=input||{};var season=resolveLeaderboardSeason_(input.seasonId),snapshot=getSnapshot_(season.SeasonID),rows={},schools=snapshot.schools;snapshot.entries.forEach(function(entry){var id=entry.schoolId||'NO_SCHOOL';if(!rows[id])rows[id]={schoolId:id,schoolName:schools[id]||'Sekolah tidak tersedia',participants:0,totalPoint:0};rows[id].participants++;rows[id].totalPoint+=entry.point;});var ranked=Object.keys(rows).map(function(id){var row=rows[id];row.averagePoint=row.participants?Math.round(row.totalPoint/row.participants):0;return row;}).sort(function(a,b){return b.totalPoint-a.totalPoint||b.averagePoint-a.averagePoint||b.participants-a.participants||a.schoolName.localeCompare(b.schoolName);});ranked.forEach(function(row,index){row.rank=index+1;delete row.schoolId;});var page=page_(ranked,input);return successResponse({season:publicLeaderboardSeason_(season),totalSchools:ranked.length,entries:page},ranked.length?'Leaderboard sekolah berhasil dimuat.':'Leaderboard sekolah belum tersedia.');}
  function getSeasons(){return successResponse(DatabaseService.getAllRows('Seasons').filter(function(row){return row.Status==='ACTIVE'||row.Status==='FINISHED'||row.Status==='ARCHIVED';}).sort(function(a,b){return dateStart_(b.StartDate)-dateStart_(a.StartDate);}).map(publicLeaderboardSeason_),'Daftar season berhasil dimuat.');}
  function getAdminLeaderboard(token,input){requireRole(token,['ADMIN','SUPERADMIN']);input=input||{};var season=resolveLeaderboardSeason_(input.seasonId),snapshot=getSnapshot_(season.SeasonID),page=page_(snapshot.entries,input);return successResponse({season:publicLeaderboardSeason_(season),totalParticipants:snapshot.entries.length,entries:page.map(function(row){return{rank:row.rank,userId:row.userId,name:row.name,schoolName:row.schoolName,point:row.point,correctAnswers:row.correctAnswers,quizCompleted:row.quizCompleted,averageScore:row.averageScore,attempt:row.attempt,fraudStatus:row.fraudStatus};})},'Leaderboard admin berhasil dimuat.');}

  function getSnapshot_(seasonId){var cache=CacheService.getScriptCache(),key=LEADERBOARD_CACHE_PREFIX+seasonId,cached=cache.get(key);if(cached){try{return JSON.parse(cached);}catch(ignore){cache.remove(key);}}var users={},schools={},points={},stats={},fraud={};DatabaseService.getAllRows('Users').forEach(function(row){users[row.UserID]=row;});DatabaseService.getAllRows('Schools').forEach(function(row){schools[row.SchoolID]=row.SchoolName;});DatabaseService.getAllRows('PointTransactions').forEach(function(row){if(row.SeasonID===seasonId&&row.Status==='VALID')points[row.UserID]=(points[row.UserID]||0)+Number(row.Point||0);});DatabaseService.getAllRows('QuizSessions').forEach(function(row){if(row.SeasonID!==seasonId||row.Status!=='COMPLETED')return;var item=stats[row.UserID]||(stats[row.UserID]={correctAnswers:0,quizCompleted:0,scoreTotal:0,attempt:0});item.correctAnswers+=Number(row.Correct||0);item.quizCompleted++;item.scoreTotal+=Number(row.Score||0);item.attempt=Math.max(item.attempt,Number(row.Attempt||0));});DatabaseService.getAllRows('FraudLogs').forEach(function(row){if(row.Status&&row.Status!=='RESOLVED')fraud[row.UserID]=row.Status;});var entries=Object.keys(points).filter(function(id){var user=users[id];return user&&user.Status==='ACTIVE'&&points[id]>0;}).map(function(id){var user=users[id],item=stats[id]||{correctAnswers:0,quizCompleted:0,scoreTotal:0,attempt:0};return{userId:id,name:user.Name,schoolId:user.SchoolID,schoolName:schools[user.SchoolID]||'',point:points[id],correctAnswers:item.correctAnswers,quizCompleted:item.quizCompleted,averageScore:item.quizCompleted?Math.round(item.scoreTotal/item.quizCompleted):0,attempt:item.attempt,fraudStatus:fraud[id]||'CLEAR'};});entries.sort(function(a,b){return b.point-a.point||b.correctAnswers-a.correctAnswers||b.quizCompleted-a.quizCompleted||b.averageScore-a.averageScore||a.userId.localeCompare(b.userId);});entries.forEach(function(row,index){row.rank=index+1;});var snapshot={entries:entries,schools:schools};try{cache.put(key,JSON.stringify(snapshot),LEADERBOARD_CACHE_TTL);}catch(ignore2){}return snapshot;}
  function page_(rows,input){var limit=Math.min(Math.max(parseInt(input.limit,10)||50,1),100),offset=Math.max(parseInt(input.offset,10)||0,0);return rows.slice(offset,offset+limit);}
  function publicEntry_(row){return{rank:row.rank,name:maskLeaderboardName_(row.name),schoolName:row.schoolName,point:row.point,correctAnswers:row.correctAnswers,quizCompleted:row.quizCompleted,averageScore:row.averageScore};}
  function resolveLeaderboardSeason_(seasonId){var seasons=DatabaseService.getAllRows('Seasons'),id=sanitizeText_(seasonId||'',40,'SeasonID'),season=id?seasons.filter(function(row){return row.SeasonID===id;})[0]:findPlayableSeasons_()[0];if(!season&&!id)season=seasons.filter(function(row){return row.Status==='FINISHED'||row.Status==='ARCHIVED';}).sort(function(a,b){return dateEnd_(b.EndDate)-dateEnd_(a.EndDate);})[0];if(!season)throw new AppError('Season tidak ditemukan.','NO_ACTIVE_SEASON');if(['ACTIVE','FINISHED','ARCHIVED'].indexOf(season.Status)<0)throw new AppError('Leaderboard season belum tersedia.','QUIZ_NOT_AVAILABLE');return season;}
  function publicLeaderboardSeason_(row){return{seasonId:row.SeasonID,name:row.Name,status:row.Status,startDate:row.StartDate,endDate:row.EndDate};}
  function seasonPointFromLedger_(userId,seasonId){return DatabaseService.getAllRows('PointTransactions').filter(function(row){return row.UserID===userId&&row.SeasonID===seasonId&&row.Status==='VALID';}).reduce(function(sum,row){return sum+Number(row.Point||0);},0);}
  return Object.freeze({getLeaderboard:getLeaderboard,getMyRank:getMyRank,getSchoolLeaderboard:getSchoolLeaderboard,getSeasons:getSeasons,getAdminLeaderboard:getAdminLeaderboard});
})();

function maskLeaderboardName_(name){var parts=String(name||'').trim().split(/\s+/).filter(Boolean);if(!parts.length)return'Peserta';return parts[0]+parts.slice(1).map(function(part){return' '+part.charAt(0).toUpperCase()+'.';}).join('');}
function invalidateLeaderboardCache_(seasonId){if(!seasonId)return;CacheService.getScriptCache().remove(LEADERBOARD_CACHE_PREFIX+seasonId);}
