var QuizService=(function(){
  function getStatus(token,input){var auth=requireStudent_(token),season=resolveSeason_(input&&input.seasonId,true);expireUserSessions_(auth.user.UserID,season);var sessions=userSeasonSessions_(auth.user.UserID,season.SeasonID),active=sessions.filter(function(row){return row.Status==='STARTED';})[0]||null,completed=sessions.filter(function(row){return row.Status==='COMPLETED';}),used=sessions.filter(function(row){return row.Status!=='INVALID';}).length,max=Number(season.MaxAttempt||1);return successResponse({season:publicSeason_(season,''),canStart:!active&&used<max,canResume:Boolean(active),completed:completed.length>0,attemptsUsed:used,maxAttempt:max,activeSessionId:active?active.SessionID:null,completedSessionId:completed.length?completed[completed.length-1].SessionID:null},'Status quiz berhasil dimuat.');}
  function start(token,input,request){return DatabaseService.withLock(function(){var auth=requireStudent_(token),season=resolveSeason_(input&&input.seasonId,true);expireUserSessions_(auth.user.UserID,season);var sessions=userSeasonSessions_(auth.user.UserID,season.SeasonID),active=sessions.filter(function(row){return row.Status==='STARTED';})[0];if(active){logActivity_(auth.user.UserID,'RESUME_QUIZ','QuizSession',active.SessionID,'Melanjutkan challenge',request.userAgent);return successResponse(sessionPayload_(active,season,auth.user.UserID),'Challenge dilanjutkan.');}var used=sessions.filter(function(row){return row.Status!=='INVALID';}).length,max=Number(season.MaxAttempt||1);if(used>=max)throw new AppError('Batas percobaan challenge telah tercapai.','MAX_ATTEMPT_REACHED');var questions=DatabaseService.getAllRows('Questions').filter(function(row){return row.Status==='ACTIVE';});var count=Number(season.QuestionCount||0);if(!count||questions.length<count)throw new AppError('Jumlah soal aktif belum mencukupi.','INSUFFICIENT_QUESTIONS');var selected=shuffle_(questions.slice()).slice(0,count).map(function(row){return row.QuestionID;}),now=nowIso_(),quiz={SessionID:generateId('QZS'),UserID:auth.user.UserID,SeasonID:season.SeasonID,StartedAt:now,FinishedAt:'',QuestionIDs:JSON.stringify(selected),Correct:0,Wrong:0,Score:0,Bonus:0,TotalPoint:0,Duration:0,Attempt:used+1,Status:'STARTED',DeviceID:request.deviceId||'',UserAgent:request.userAgent||'',CreatedAt:now,UpdatedAt:now};DatabaseService.insert('QuizSessions',quiz);logActivity_(auth.user.UserID,'START_QUIZ','QuizSession',quiz.SessionID,'Memulai challenge','');return successResponse(sessionPayload_(quiz,season,auth.user.UserID),'Challenge dimulai.');});}
  function getCurrentQuestion(token,input){var auth=requireStudent_(token),quiz=ownedQuiz_(auth.user.UserID,input&&input.quizSessionId),season=resolveSeason_(quiz.SeasonID,false);ensureStarted_(quiz,season);return successResponse(sessionPayload_(quiz,season,auth.user.UserID),'Soal berhasil dimuat.');}
  function submitAnswer(token,input){return DatabaseService.withLock(function(){var auth=requireStudent_(token),quiz=ownedQuiz_(auth.user.UserID,input&&input.quizSessionId),season=resolveSeason_(quiz.SeasonID,false);ensureStarted_(quiz,season);var questionId=sanitizeText_(input&&input.questionId,40,'QuestionID'),snapshot=parseQuestionIds_(quiz);if(snapshot.indexOf(questionId)<0)throw new AppError('Pertanyaan bukan bagian dari session.','QUESTION_NOT_IN_SESSION');var previous=answerFor_(quiz.SessionID,questionId);if(previous)throw new AppError('Pertanyaan sudah dijawab.','QUESTION_ALREADY_ANSWERED');var question=DatabaseService.findById('Questions','QuestionID',questionId);if(!question)throw new AppError('Pertanyaan tidak ditemukan.','QUESTION_NOT_FOUND');var selected=resolveOption_(quiz.SessionID,question,input&&input.selectedOption);if(!selected)throw new AppError('Pilihan jawaban tidak valid.','INVALID_OPTION');var correct=selected.letter===String(question.CorrectAnswer).toUpperCase(),point=correct?Number(question.Point||season.PointPerQuestion||0):0,now=nowIso_(),lastAt=lastAnswerTime_(quiz.SessionID)||quiz.StartedAt,responseTime=Math.max(0,new Date(now).getTime()-new Date(lastAt).getTime());DatabaseService.insert('QuizAnswers',{AnswerID:generateId('ANS'),SessionID:quiz.SessionID,UserID:auth.user.UserID,QuestionID:questionId,SelectedAnswer:selected.letter,IsCorrect:correct,Point:point,AnsweredAt:now,ResponseTimeMs:responseTime,Status:'VALID'});logActivity_(auth.user.UserID,'ANSWER_QUESTION','QuizSession',quiz.SessionID,'Menjawab pertanyaan '+questionId,'');var answered=validAnswers_(quiz.SessionID),done=answered.length===snapshot.length,result=done?finalize_(quiz,season,auth.user.UserID):null,data={accepted:true,point:point,completed:done,answered:answered.length,totalQuestions:snapshot.length};if(toBoolean_(season.ShowExplanation)){data.isCorrect=correct;data.correctAnswer=String(question['Option'+String(question.CorrectAnswer).toUpperCase()]||'');data.explanation=question.Explanation||'';}if(result)data.result=result;return successResponse(data,done?'Challenge selesai.':'Jawaban diterima.');});}
  function finish(token,input){return DatabaseService.withLock(function(){var auth=requireStudent_(token),quiz=ownedQuiz_(auth.user.UserID,input&&input.quizSessionId),season=resolveSeason_(quiz.SeasonID,false);if(quiz.Status==='COMPLETED'){var reconciled=ensureCompletedAward_(quiz,season,auth.user.UserID);return successResponse(resultPayload_(quiz,auth.user.UserID,reconciled),'Hasil quiz berhasil dimuat.');}ensureStarted_(quiz,season);if(validAnswers_(quiz.SessionID).length!==parseQuestionIds_(quiz).length)throw new AppError('Masih ada pertanyaan yang belum dijawab.','QUIZ_NOT_AVAILABLE');return successResponse(finalize_(quiz,season,auth.user.UserID),'Challenge selesai.');});}
  function getResult(token,input){return DatabaseService.withLock(function(){var auth=requireStudent_(token),quiz=ownedQuiz_(auth.user.UserID,input&&input.quizSessionId);if(quiz.Status!=='COMPLETED')throw new AppError('Quiz belum selesai.','QUIZ_NOT_AVAILABLE');var season=DatabaseService.findById('Seasons','SeasonID',quiz.SeasonID);if(!season)throw new AppError('Season tidak ditemukan.','QUIZ_NOT_AVAILABLE');var reconciled=ensureCompletedAward_(quiz,season,auth.user.UserID);return successResponse(resultPayload_(quiz,auth.user.UserID,reconciled),'Hasil quiz berhasil dimuat.');});}
  function getMySeasonStats(token,input){var auth=requireStudent_(token),season=resolveSeason_(input&&input.seasonId,true),completed=userSeasonSessions_(auth.user.UserID,season.SeasonID).filter(function(row){return row.Status==='COMPLETED';}),correct=completed.reduce(function(sum,row){return sum+Number(row.Correct||0);},0),average=completed.length?Math.round(completed.reduce(function(sum,row){return sum+Number(row.Score||0);},0)/completed.length):0;return successResponse({seasonId:season.SeasonID,seasonPoint:PointService.getSeasonPoint(auth.user.UserID,season.SeasonID),totalPoint:Number(DatabaseService.findById('Users','UserID',auth.user.UserID).TotalPointCache||0),quizCompleted:completed.length,correctAnswers:correct,averageScore:average},'Statistik season berhasil dimuat.');}

  function finalize_(quiz,season,userId){var answers=validAnswers_(quiz.SessionID),questions=parseQuestionIds_(quiz),correct=answers.filter(function(row){return isTrue_(row.IsCorrect);}).length,wrong=questions.length-correct,score=questions.length?Math.round(correct/questions.length*100):0,quizPoint=answers.reduce(function(sum,row){return sum+Number(row.Point||0);},0),bonus=correct===questions.length?Number(getSetting_('PERFECT_SCORE_BONUS',0)):0,finished=nowIso_(),duration=Math.max(0,Math.round((new Date(finished).getTime()-new Date(quiz.StartedAt).getTime())/1000)),total=quizPoint+bonus;DatabaseService.updateById('QuizSessions','SessionID',quiz.SessionID,{FinishedAt:finished,Correct:correct,Wrong:wrong,Score:score,Bonus:bonus,TotalPoint:total,Duration:duration,Status:'COMPLETED',UpdatedAt:finished});quiz=DatabaseService.findById('QuizSessions','SessionID',quiz.SessionID);var totalPoint=PointService.awardQuiz(userId,season,quiz,quizPoint,bonus);logActivity_(userId,'FINISH_QUIZ','QuizSession',quiz.SessionID,'Menyelesaikan challenge','');return resultPayload_(quiz,userId,totalPoint);}
  function ensureCompletedAward_(quiz,season,userId){return PointService.awardQuiz(userId,season,quiz,Math.max(0,Number(quiz.TotalPoint||0)-Number(quiz.Bonus||0)),Number(quiz.Bonus||0));}
  function resultPayload_(quiz,userId,totalPoint){return{quizSessionId:quiz.SessionID,seasonId:quiz.SeasonID,correct:Number(quiz.Correct),wrong:Number(quiz.Wrong),score:Number(quiz.Score),bonus:Number(quiz.Bonus),point:Number(quiz.TotalPoint),duration:Number(quiz.Duration),totalPoint:totalPoint===undefined?Number(DatabaseService.findById('Users','UserID',userId).TotalPointCache||0):totalPoint};}
  function sessionPayload_(quiz,season,userId){var question=currentQuestion_(quiz),answered=validAnswers_(quiz.SessionID).length,total=parseQuestionIds_(quiz).length,remaining=remainingSeconds_(quiz,season);return{quizSessionId:quiz.SessionID,season:{SeasonID:season.SeasonID,Name:season.Name,Theme:season.Theme,QuizDuration:Number(season.QuizDuration||0),ShowExplanation:toBoolean_(season.ShowExplanation)},attempt:Number(quiz.Attempt),answered:answered,totalQuestions:total,remainingSeconds:remaining,question:question?publicQuestion_(quiz.SessionID,question,answered,total):null};}
  function currentQuestion_(quiz){var answered={};validAnswers_(quiz.SessionID).forEach(function(row){answered[row.QuestionID]=true;});var id=parseQuestionIds_(quiz).filter(function(questionId){return !answered[questionId];})[0];return id?DatabaseService.findById('Questions','QuestionID',id):null;}
  function publicQuestion_(sessionId,question,index,total){return{questionId:question.QuestionID,question:question.Question,category:question.Category,index:index+1,total:total,options:optionMap_(sessionId,question).map(function(option){return{id:option.id,text:option.text};})};}
  function optionMap_(sessionId,question){var secret=quizOptionSecret_();return['A','B','C','D'].map(function(letter){return{letter:letter,id:'opt_'+sha256Hex_(secret+'|id|'+sessionId+'|'+question.QuestionID+'|'+letter).slice(0,16),text:String(question['Option'+letter]||''),order:sha256Hex_(secret+'|order|'+sessionId+'|'+question.QuestionID+'|'+letter)};}).sort(function(a,b){return a.order.localeCompare(b.order);});}
  function resolveOption_(sessionId,question,optionId){return optionMap_(sessionId,question).filter(function(option){return option.id===String(optionId);})[0]||null;}
  function ensureStarted_(quiz,season){if(quiz.Status==='COMPLETED')throw new AppError('Quiz sudah selesai.','QUIZ_ALREADY_COMPLETED');if(quiz.Status==='EXPIRED')throw new AppError('Waktu quiz telah berakhir.','QUIZ_SESSION_EXPIRED');if(quiz.Status!=='STARTED')throw new AppError('Quiz tidak tersedia.','QUIZ_NOT_AVAILABLE');if(Date.now()<dateStart_(season.StartDate))throw new AppError('Season belum dimulai.','SEASON_NOT_STARTED');if(Date.now()>dateEnd_(season.EndDate)){expireQuiz_(quiz);throw new AppError('Season telah berakhir.','SEASON_ENDED');}if(remainingSeconds_(quiz,season)===0&&Number(season.QuizDuration||0)>0){expireQuiz_(quiz);throw new AppError('Waktu quiz telah berakhir.','QUIZ_SESSION_EXPIRED');}}
  function expireUserSessions_(userId,season){userSeasonSessions_(userId,season.SeasonID).filter(function(row){return row.Status==='STARTED'&&remainingSeconds_(row,season)===0&&Number(season.QuizDuration||0)>0;}).forEach(expireQuiz_);}
  function expireQuiz_(quiz){DatabaseService.updateById('QuizSessions','SessionID',quiz.SessionID,{Status:'EXPIRED',FinishedAt:nowIso_(),UpdatedAt:nowIso_()});logActivity_(quiz.UserID,'QUIZ_EXPIRED','QuizSession',quiz.SessionID,'Waktu challenge berakhir','');}
  function remainingSeconds_(quiz,season){var duration=Number(season.QuizDuration||0);if(duration<=0)return 0;return Math.max(0,duration-Math.floor((Date.now()-new Date(quiz.StartedAt).getTime())/1000));}
  function resolveSeason_(seasonId,mustBePlayable){var season;if(seasonId)season=DatabaseService.findById('Seasons','SeasonID',sanitizeText_(seasonId,40,'SeasonID'));else season=findPlayableSeasons_()[0];if(!season)throw new AppError('Season aktif tidak ditemukan.','NO_ACTIVE_SEASON');if(season.Status!=='ACTIVE')throw new AppError('Quiz tidak tersedia.','QUIZ_NOT_AVAILABLE');if(mustBePlayable){if(Date.now()<dateStart_(season.StartDate))throw new AppError('Season belum dimulai.','SEASON_NOT_STARTED');if(Date.now()>dateEnd_(season.EndDate))throw new AppError('Season telah berakhir.','SEASON_ENDED');}return season;}
  function requireStudent_(token){var auth=requireAuth(token);if(auth.user.Role!=='STUDENT')throw new AppError('Quiz hanya tersedia untuk peserta.','FORBIDDEN');return auth;}
  function ownedQuiz_(userId,id){var quiz=DatabaseService.findById('QuizSessions','SessionID',sanitizeText_(id,40,'QuizSessionID'));if(!quiz||quiz.UserID!==userId)throw new AppError('Quiz session tidak ditemukan.','QUIZ_SESSION_NOT_FOUND');return quiz;}
  function userSeasonSessions_(userId,seasonId){return DatabaseService.getAllRows('QuizSessions').filter(function(row){return row.UserID===userId&&row.SeasonID===seasonId;});}
  function validAnswers_(sessionId){return DatabaseService.getAllRows('QuizAnswers').filter(function(row){return row.SessionID===sessionId&&row.Status==='VALID';});}
  function answerFor_(sessionId,questionId){return validAnswers_(sessionId).filter(function(row){return row.QuestionID===questionId;})[0]||null;}
  function lastAnswerTime_(sessionId){var rows=validAnswers_(sessionId);return rows.length?rows[rows.length-1].AnsweredAt:'';}
  function parseQuestionIds_(quiz){try{var ids=JSON.parse(quiz.QuestionIDs);return Array.isArray(ids)?ids:[];}catch(ignore){throw new AppError('Snapshot pertanyaan tidak valid.','QUIZ_NOT_AVAILABLE');}}
  function shuffle_(rows){for(var i=rows.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),tmp=rows[i];rows[i]=rows[j];rows[j]=tmp;}return rows;}
  function isTrue_(value){return value===true||String(value).toLowerCase()==='true';}
  function quizOptionSecret_(){var properties=PropertiesService.getScriptProperties(),secret=properties.getProperty('QUIZ_OPTION_SECRET');if(!secret){secret=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');properties.setProperty('QUIZ_OPTION_SECRET',secret);}return secret;}
  return Object.freeze({getStatus:getStatus,start:start,getCurrentQuestion:getCurrentQuestion,submitAnswer:submitAnswer,finish:finish,getResult:getResult,getMySeasonStats:getMySeasonStats});
})();
