var SessionService=(function(){
  function createSession(user,request){return DatabaseService.withLock(function(){var token=generateSessionToken_();var now=new Date();var ttl=Number(getSetting_('SESSION_TTL_SECONDS',86400));DatabaseService.insert('Sessions',{SessionToken:sha256Hex_(token),UserID:user.UserID,Role:user.Role,CreatedAt:now.toISOString(),ExpiredAt:new Date(now.getTime()+ttl*1000).toISOString(),LastActivityAt:now.toISOString(),Status:'ACTIVE',UserAgent:request.userAgent||'',DeviceID:request.deviceId||''});return{token:token,expiresAt:new Date(now.getTime()+ttl*1000).toISOString()};});}
  function validateSession(token){if(!token)throw new AppError('Session tidak valid.','SESSION_INVALID');var digest=sha256Hex_(token);var session=DatabaseService.findOne('Sessions','SessionToken',digest);if(!session||session.Status!=='ACTIVE')throw new AppError('Session tidak valid.','SESSION_INVALID');if(new Date(session.ExpiredAt).getTime()<=Date.now()){DatabaseService.updateById('Sessions','SessionToken',digest,{Status:'EXPIRED',LastActivityAt:nowIso_()});logActivity_(session.UserID,'SESSION_EXPIRED','Session',digest.slice(0,12),'Session kedaluwarsa','');throw new AppError('Session telah kedaluwarsa.','SESSION_EXPIRED');}var user=DatabaseService.findById('Users','UserID',session.UserID);if(!user)throw new AppError('Session tidak valid.','SESSION_INVALID');return{session:session,user:user,digest:digest};}
  function revokeSession(token){var auth=validateSession(token);DatabaseService.updateById('Sessions','SessionToken',auth.digest,{Status:'REVOKED',LastActivityAt:nowIso_()});return auth;}
  function refreshSessionActivity(token){var auth=validateSession(token);DatabaseService.updateById('Sessions','SessionToken',auth.digest,{LastActivityAt:nowIso_()});return auth;}
  function generateSessionToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
  return Object.freeze({createSession:createSession,validateSession:validateSession,revokeSession:revokeSession,refreshSessionActivity:refreshSessionActivity});
})();

function requireAuth(token){var auth=SessionService.validateSession(token);if(auth.user.Status==='BLOCKED')throw new AppError('Akun diblokir.','USER_BLOCKED');if(auth.user.Status==='SUSPENDED')throw new AppError('Akun ditangguhkan.','USER_SUSPENDED');DatabaseService.updateById('Sessions','SessionToken',auth.digest,{LastActivityAt:nowIso_()});return auth;}
function requireRole(token,allowedRoles){var auth=requireAuth(token);if(allowedRoles.indexOf(auth.user.Role)<0)throw new AppError('Anda tidak memiliki izin.','FORBIDDEN');return auth;}
