var WinnerService=(function(){
  var roles=['ADMIN','SUPERADMIN'],finalStatuses=['PENDING_REVIEW','VALIDATED','PUBLISHED'];
  function prepare(token,input){var auth=requireRole(token,roles),season=winnerSeason_(input,auth),data=preview_(season);logActivity_(auth.user.UserID,'PREPARE_FINALIZATION','Season',season.SeasonID,'Menyiapkan finalisasi season','');return successResponse(data,data.status==='NO_VALID_WINNER'?'Tidak ada peserta yang memenuhi syarat.':'Preview finalisasi berhasil dimuat.');}
  function disqualify(token,input){var auth=requireRole(token,roles),season=winnerSeason_(input,auth),userId=sanitizeText_(input&&input.userId,40,'UserID'),reason=requiredReason_(input&&input.reason),candidate=LeaderboardService.buildSeasonLeaderboard(season.SeasonID).filter(function(row){return row.userId===userId;})[0];if(!candidate)throw new AppError('Kandidat tidak ditemukan.','NO_VALID_WINNER');return DatabaseService.withLock(function(){var existing=DatabaseService.getAllRows('Winners').filter(function(row){return row.SeasonID===season.SeasonID&&row.UserID===userId&&row.Status==='DISQUALIFIED';})[0];if(!existing){existing=winnerRow_(season,candidate,auth.user.UserID,'DISQUALIFIED',reason);DatabaseService.insert('Winners',existing);}invalidateWinnerCaches_(season.SeasonID);logActivity_(auth.user.UserID,'DISQUALIFY_CANDIDATE','Season',season.SeasonID,'Diskualifikasi '+userId+': '+reason,'');return successResponse({disqualified:publicAdminWinner_(existing),next:preview_(season)},'Kandidat didiskualifikasi.');});}
  function finalize(token,input){var auth=requireRole(token,roles),season=winnerSeason_(input,auth),userId=sanitizeText_(input&&input.userId,40,'UserID'),reason=sanitizeText_(input&&input.reason||'',500,'Reason');return DatabaseService.withLock(function(){var existing=finalWinner_(season.SeasonID);if(existing){var existingReward=rewardForWinner_(existing,season,input);return successResponse({winner:publicAdminWinner_(existing),reward:existingReward},'Winner sudah ditetapkan.');}var preview=preview_(season);if(preview.status==='NO_VALID_WINNER')throw new AppError('Tidak ada peserta yang memenuhi syarat.','NO_VALID_WINNER');var candidates=preview.candidates||[preview.candidate],candidate=candidates.filter(function(row){return row.userId===userId;})[0];if(!candidate)throw new AppError('User bukan kandidat pemenang.','INVALID_WINNER_CANDIDATE');if((preview.status==='NEED_REVIEW'||candidate.fraudStatus==='HIGH_RISK')&&!reason)throw new AppError('Alasan pemilihan wajib diisi.','VALIDATION_ERROR');var winner=winnerRow_(season,candidate,auth.user.UserID,'PENDING_REVIEW',reason);DatabaseService.insert('Winners',winner);var reward=rewardForWinner_(winner,season,input);logActivity_(auth.user.UserID,'FINALIZE_WINNER','Winner',winner.WinnerID,'Menetapkan winner '+userId+(reason?': '+reason:''),'');invalidateWinnerCaches_(season.SeasonID);return successResponse({winner:publicAdminWinner_(winner),reward:reward},'Winner berhasil ditetapkan dan menunggu verifikasi.');});}
  function verify(token,input){var auth=requireRole(token,roles),winner=requireFinalWinner_(input&&input.winnerId,input&&input.seasonId);if(winner.Status==='PUBLISHED'||winner.Status==='VALIDATED')return successResponse(finalAdminPayload_(winner),'Winner sudah diverifikasi.');if(winner.Status!=='PENDING_REVIEW')throw new AppError('Status winner tidak dapat diverifikasi.','INVALID_WINNER_STATUS');var user=DatabaseService.findById('Users','UserID',winner.UserID),reward=rewardByWinner_(winner.WinnerID),destination=sanitizeText_(input&&input.destinationNumber||user&&user.WhatsApp||'',30,'Nomor tujuan');if(!destination)throw new AppError('Nomor tujuan hadiah wajib diisi.','VALIDATION_ERROR');DatabaseService.withLock(function(){DatabaseService.updateById('Winners','WinnerID',winner.WinnerID,{Status:'VALIDATED',Notes:appendNote_(winner.Notes,input&&input.notes)});DatabaseService.updateById('Rewards','RewardID',reward.RewardID,{DestinationNumber:destination,Provider:sanitizeText_(input&&input.provider||reward.Provider||'',60,'Provider'),Status:'VERIFIED',Notes:appendNote_(reward.Notes,input&&input.notes),UpdatedAt:nowIso_()});});logActivity_(auth.user.UserID,'VERIFY_WINNER','Winner',winner.WinnerID,'Verifikasi identitas dan hadiah','');return successResponse(finalAdminPayload_(DatabaseService.findById('Winners','WinnerID',winner.WinnerID)),'Winner berhasil diverifikasi.');}
  function updateReward(token,input){var auth=requireRole(token,roles),reward=DatabaseService.findById('Rewards','RewardID',sanitizeText_(input&&input.rewardId,40,'RewardID'));if(!reward)throw new AppError('Reward tidak ditemukan.','REWARD_NOT_FOUND');var next=sanitizeText_(input&&input.status,20,'Status').toUpperCase();ValidationService.validateEnum(next,DATABASE_ENUMS.RewardStatus,'Status reward');var allowed={WAITING:['VERIFIED','FAILED'],VERIFIED:['SENT','FAILED'],SENT:['COMPLETED','FAILED'],FAILED:['VERIFIED'],COMPLETED:[]},override=auth.user.Role==='SUPERADMIN'&&input&&input.override===true;if(!override&&(allowed[reward.Status]||[]).indexOf(next)<0&&next!==reward.Status)throw new AppError('Transisi status reward tidak valid.','INVALID_REWARD_TRANSITION');var changes={Status:next,Notes:appendNote_(reward.Notes,input&&input.notes),UpdatedAt:nowIso_()};if(next==='SENT'&&!reward.SentAt)changes.SentAt=nowIso_();DatabaseService.updateById('Rewards','RewardID',reward.RewardID,changes);logActivity_(auth.user.UserID,'UPDATE_REWARD','Reward',reward.RewardID,'Status reward '+reward.Status+' → '+next,'');return successResponse(DatabaseService.findById('Rewards','RewardID',reward.RewardID),'Status reward diperbarui.');}
  function publish(token,input){var auth=requireRole(token,roles),winner=requireFinalWinner_(input&&input.winnerId,input&&input.seasonId);if(winner.Status==='PUBLISHED')return successResponse(publicWinner_(winner),'Winner sudah dipublikasikan.');if(winner.Status!=='VALIDATED')throw new AppError('Winner harus diverifikasi sebelum dipublikasikan.','INVALID_WINNER_STATUS');DatabaseService.updateById('Winners','WinnerID',winner.WinnerID,{Status:'PUBLISHED',Notes:appendNote_(winner.Notes,'PublishedAt='+nowIso_())});logActivity_(auth.user.UserID,'PUBLISH_WINNER','Winner',winner.WinnerID,'Mempublikasikan pemenang','');return successResponse(publicWinner_(DatabaseService.findById('Winners','WinnerID',winner.WinnerID)),'Winner berhasil dipublikasikan.');}
  function getPublished(input){var seasonId=sanitizeText_(input&&input.seasonId||'',40,'SeasonID'),all=DatabaseService.getAllRows('Winners').filter(function(row){return !seasonId||row.SeasonID===seasonId;}).sort(function(a,b){return new Date(b.SelectedAt)-new Date(a.SelectedAt);}),winner=all.filter(function(row){return row.Status==='PUBLISHED';})[0];if(winner)return successResponse(publicWinner_(winner),'Winner ditemukan.');var pending=all.filter(function(row){return finalStatuses.indexOf(row.Status)>=0;})[0],season=pending&&DatabaseService.findById('Seasons','SeasonID',pending.SeasonID);return successResponse(pending?{status:'VERIFYING',seasonId:pending.SeasonID,seasonName:season&&season.Name||''}:null,'Pemenang sedang dalam proses verifikasi.');}
  function history(input){var limit=Math.min(Math.max(parseInt(input&&input.limit,10)||20,1),50),rows=DatabaseService.getAllRows('Winners').filter(function(row){return row.Status==='PUBLISHED';}).sort(function(a,b){return new Date(b.SelectedAt)-new Date(a.SelectedAt);}).slice(0,limit).map(publicWinner_);return successResponse(rows,rows.length?'Riwayat pemenang berhasil dimuat.':'Belum ada pemenang dipublikasikan.');}
  function preview_(season){var leaderboard=LeaderboardService.buildSeasonLeaderboard(season.SeasonID),disqualified={};DatabaseService.getAllRows('Winners').forEach(function(row){if(row.SeasonID===season.SeasonID&&row.Status==='DISQUALIFIED')disqualified[row.UserID]=true;});var eligible=leaderboard.filter(function(row){return !disqualified[row.userId];}).map(function(row){return candidate_(row);}),completed=DatabaseService.getAllRows('QuizSessions').filter(function(row){return row.SeasonID===season.SeasonID&&row.Status==='COMPLETED';}).length;if(!eligible.length)return{season:winnerSeasonPublic_(season),statistics:{totalParticipants:leaderboard.length,totalCompleted:completed,totalValidParticipants:0},status:'NO_VALID_WINNER',candidate:null,candidates:[]};var top=eligible[0],ties=eligible.filter(function(row){return sameCompetitiveScore_(row,top);}),status=ties.length>1?'NEED_REVIEW':top.fraudStatus==='HIGH_RISK'?'REVIEW':'NORMAL';return{season:winnerSeasonPublic_(season),statistics:{totalParticipants:leaderboard.length,totalCompleted:completed,totalValidParticipants:eligible.length},status:status,candidate:top,candidates:ties};}
  function candidate_(row){var user=DatabaseService.findById('Users','UserID',row.userId),threshold=Number(getSetting_('FRAUD_HIGH_RISK_THRESHOLD',51)),logs=DatabaseService.getAllRows('FraudLogs').filter(function(log){return log.UserID===row.userId&&log.Status!=='RESOLVED';}),fraud=Number(user&&user.FraudScore||0)>=threshold?'HIGH_RISK':logs.length?'REVIEW':'NORMAL';return{rank:row.rank,userId:row.userId,name:row.name,schoolName:row.schoolName,point:row.point,correctAnswers:row.correctAnswers,quizCompleted:row.quizCompleted,averageScore:row.averageScore,fraudStatus:fraud};}
  function winnerSeason_(input,auth){var id=sanitizeText_(input&&input.seasonId,40,'SeasonID'),season=DatabaseService.findById('Seasons','SeasonID',id);if(!season)throw new AppError('Season tidak ditemukan.','NO_ACTIVE_SEASON');var finished=season.Status==='FINISHED'||season.Status==='ARCHIVED'||Date.now()>dateEnd_(season.EndDate),override=auth.user.Role==='SUPERADMIN'&&input&&input.override===true;if(!finished&&!override)throw new AppError('Season belum selesai.','SEASON_NOT_FINISHED');return season;}
  function candidateById_(season,userId){return LeaderboardService.buildSeasonLeaderboard(season.SeasonID).filter(function(row){return row.userId===userId;})[0];}
  function winnerRow_(season,candidate,adminId,status,notes){return{WinnerID:generateId('WIN'),SeasonID:season.SeasonID,UserID:candidate.userId,Rank:candidate.rank,Point:candidate.point,CorrectAnswers:candidate.correctAnswers,QuizCompleted:candidate.quizCompleted,AverageScore:candidate.averageScore,Reward:season.Reward||'',Status:status,SelectedAt:nowIso_(),SelectedBy:adminId,Notes:notes||''};}
  function rewardForWinner_(winner,season,input){var existing=rewardByWinner_(winner.WinnerID);if(existing)return existing;var row={RewardID:generateId('RWD'),SeasonID:season.SeasonID,WinnerID:winner.WinnerID,RewardName:season.Reward||'Hadiah season',Nominal:Number(input&&input.rewardNominal||0),DestinationNumber:'',Provider:'',Status:'WAITING',SentAt:'',Notes:'',CreatedAt:nowIso_(),UpdatedAt:nowIso_()};DatabaseService.insert('Rewards',row);return row;}
  function finalWinner_(seasonId){return DatabaseService.getAllRows('Winners').filter(function(row){return row.SeasonID===seasonId&&finalStatuses.indexOf(row.Status)>=0;})[0]||null;}
  function requireFinalWinner_(winnerId,seasonId){var winner=winnerId?DatabaseService.findById('Winners','WinnerID',sanitizeText_(winnerId,40,'WinnerID')):finalWinner_(sanitizeText_(seasonId,40,'SeasonID'));if(!winner)throw new AppError('Winner tidak ditemukan.','WINNER_NOT_FOUND');return winner;}
  function rewardByWinner_(winnerId){return DatabaseService.findOne('Rewards','WinnerID',winnerId);}
  function finalAdminPayload_(winner){return{winner:publicAdminWinner_(winner),reward:rewardByWinner_(winner.WinnerID)};}
  function publicAdminWinner_(row){return{winnerId:row.WinnerID,seasonId:row.SeasonID,userId:row.UserID,rank:Number(row.Rank),point:Number(row.Point),correctAnswers:Number(row.CorrectAnswers),quizCompleted:Number(row.QuizCompleted),averageScore:Number(row.AverageScore),reward:row.Reward,status:row.Status,selectedAt:row.SelectedAt,selectedBy:row.SelectedBy,notes:row.Notes};}
  function publicWinner_(winner){var user=DatabaseService.findById('Users','UserID',winner.UserID),school=user?DatabaseService.findById('Schools','SchoolID',user.SchoolID):null,season=DatabaseService.findById('Seasons','SeasonID',winner.SeasonID),reward=rewardByWinner_(winner.WinnerID),publishedAt=publishedAt_(winner);return{seasonId:winner.SeasonID,seasonName:season&&season.Name||'',winnerName:maskLeaderboardName_(user&&user.Name||''),schoolName:school&&school.SchoolName||'',point:Number(winner.Point),rewardName:reward&&reward.RewardName||winner.Reward||'',publishedAt:publishedAt};}
  function publishedAt_(winner){var match=String(winner.Notes||'').match(/PublishedAt=([^\s;]+)/);return match?match[1]:winner.SelectedAt;}
  function winnerSeasonPublic_(season){return{seasonId:season.SeasonID,name:season.Name,status:season.Status,reward:season.Reward};}
  function sameCompetitiveScore_(a,b){return a.point===b.point&&a.correctAnswers===b.correctAnswers&&a.quizCompleted===b.quizCompleted&&a.averageScore===b.averageScore;}
  function requiredReason_(value){var reason=sanitizeText_(value||'',500,'Reason');if(!reason)throw new AppError('Alasan wajib diisi.','VALIDATION_ERROR');return reason;}
  function appendNote_(oldValue,newValue){var note=sanitizeText_(newValue||'',500,'Notes');return[String(oldValue||'').trim(),note].filter(Boolean).join('; ');}
  function invalidateWinnerCaches_(seasonId){invalidateLeaderboardCache_(seasonId);CacheService.getScriptCache().remove('WINNER_CANDIDATE_V1_'+seasonId);}
  return Object.freeze({prepare:prepare,disqualify:disqualify,finalize:finalize,verify:verify,updateReward:updateReward,publish:publish,getPublished:getPublished,history:history});
})();
